### ISSUE TITLE
KeyboardProvider component not working with android

### ISSUE THREAD

**Issue by affansk** [kirillzyusko/react-native-keyboard-controller#100]
KeyboardProvider component not working with android but works with IOS

<GestureHandlerRootView style={{ flex: 1 }}>
      <KeyboardProvider>
//// my navigation</KeyboardProvider>
    </GestureHandlerRootView>

**Comment by kirillzyusko** [comment]
Hi @affansk 
It should work with android. You can clone and run `example` app (https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/example/src/App.tsx) to test it.
At least it works on Android emulators with 25-32 APIs and on my own Xiaomi Redmi Note 5 Pro.

Would you mind to share more information according to [template](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by affansk** [comment]
I guess this was happening because of keyboard avoiding view. i guess its working. 
@kirillzyusko  you can close this 

Thanks

**Comment by kirillzyusko** [comment]
Thank you @affansk 
I will check whether there is any conflicts with KeyboardAvoidingView later👍
