### ISSUE TITLE
Error when I run unit test

### ISSUE THREAD

**Issue by oularrea** [kirillzyusko/react-native-keyboard-controller#101]
**Describe the bug**
 The package 'react-native-keyboard-controller' doesn't seem to be linked. Make sure

**Code snippet**
![image](https://user-images.githubusercontent.com/15090002/205457539-69ee1886-4bf3-405c-b1e6-3bdea1df4a64.png)

**Repo for reproducing**
I would be highly appreciate if you can provide repository for reproducing your issue. It can significantly reduce the time for discovering and fixing the problem.

**Smartphone (please complete the following information):**
 - Desktop OS:  MacOS 13.0.1 (22A400)
 - Device: Testing with Jest
 - RN version: 0.70.5
 - Library version: 1.4.1

**Comment by kirillzyusko** [comment]
Interesting 🤔 
I thought unit tests should be running without any issues, since this library depends on modules, that are already mocked.
I will have a look on it now 👀
