### ISSUE TITLE
can not run example

### ISSUE THREAD

**Issue by fukemy** [kirillzyusko/react-native-keyboard-controller#108]
**Describe the bug**
I can not run the example with android + ios

Android error:

```
Error: react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
  • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.
  • Rebuild and re-run the app.
  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
  If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-device-info/react-native-device-info
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

IOS error:
```
 ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```
**Code snippet**
Add your code snippet where error has been occurred.

**Repo for reproducing**
I would be highly appreciate if you can provide repository for reproducing your issue. It can significantly reduce the time for discovering and fixing the problem.

**To Reproduce**
1. Yarn
2. run pod using terminal( because im using m1)
3. cd example
4. yarn android/ yarn ios 

**Smartphone (please complete the following information):**
 - Desktop OS: Mac OS 12.6
 - Device: simulator 16.0 + emulator android 33
 - OS: ios + android
 - RN version: 0.681
 - RN architecture: [e.g. old/new or paper/fabric]
 - JS engine: JSC
 - Library version: lasted

**Additional context**

<img width="1512" alt="Screen Shot 2022-12-23 at 15 24 56" src="https://user-images.githubusercontent.com/8202437/209300431-3e4a18f4-06a4-427b-8ae5-947a64ed6e28.png">

**Comment by kirillzyusko** [comment]
@fukemy could you please start a new metro bundler (and close current one) via `yarn start -- --reset-cache` command?
Seems like you are running example app, but metro bundler is assembling another application (not example).

**Comment by fukemy** [comment]
yarh, it's work now, thanks
