### ISSUE TITLE
[QUESTION] How to find out the height of the keyboard without opening it?

### ISSUE THREAD

**Issue by dualism98** [kirillzyusko/react-native-keyboard-controller#131]
**Describe the bug**
I'm so sorry, buy I need you help, please
In my application, I need to implement a menu similar to the sticker menu, as in telegram. Accordingly, it should be possible to open without opening the keyboard. And the height of the menu should be equal to the height of the keyboard.

**Expected behavior**
There is some value of keyboard height from hook or something.

**Screenshots**
![IMG_7614](https://user-images.githubusercontent.com/58901926/227912255-5278775f-5337-45a1-b2d8-34d8f09825c0.jpg)
![IMG_7615](https://user-images.githubusercontent.com/58901926/227912291-8d61aa8a-262d-4dd7-963c-b787ce18671b.jpg)

**Additional context**
Here is a video of how I want to

https://user-images.githubusercontent.com/58901926/227913268-713f085e-d0db-47f7-83ab-f8f8fadf9fe5.mp4

**Comment by kirillzyusko** [comment]
No @dualism98 
As far as I know it's impossible to know keyboard size if it's not going to be shown. So for your case it's better to store the value of last keyboard size and update it correspondingly to keep it up to date.

Can I close the issue, since I answered the question?

**Comment by dualism98** [comment]
Of course. And thank you very much for your help!

**Comment by fukemy** [comment]
I found some big problem with Android, to avoid keyboard jump when change keyboard mode( eg: from normal keyboard to emoji keyboard). We must change the keyboard adjust to `adjust nothing`, which mean all the keyboard height listener will not working. Any ideal pls

**Comment by kirillzyusko** [comment]
@fukemy please, open a new issue.

Basically you don't need to use `adjustNothing` - once you've wrapped your app in `KeyboardProvider` all automatic resizes by Android OS will not happen anymore.

> to avoid keyboard jump when change keyboard mode

When keyboard changes its size the library makes an animated transition. You can check [Chat](https://github.com/kirillzyusko/react-native-keyboard-controller/tree/main/example/src/screens/Examples/ReanimatedChat) example as a reference 👀

**Comment by fukemy** [comment]
Hi @kirillzyusko , I make new question for continue this issue, please double check it
