### ISSUE TITLE
KeyboardProvider breaks translucent StatusBar on Android

### ISSUE THREAD

**Issue by hirbod** [kirillzyusko/react-native-keyboard-controller#14]
**Describe the bug**

My StatusBar is translucent in my android app. As soon as I add KeyboardProvider, it reverts that and leaves a white StatusBar which is not covering the app anymore.

**Code snippet**

Wrap the app with `<KeyboardProvider>`

**Comment by kirillzyusko** [comment]
Hi @hirbod 

Could you post a minimal reproduction demo? I'm always specifying translucent status bar like:

```tsx
<StatusBar
    translucent
    backgroundColor="rgba(0,0,0,0)"
    barStyle="dark-content"
/>
```

And in this case status bar is fully translucent, even with `<KeyboardProvider>` in the root:

<img width="198" alt="image" src="https://user-images.githubusercontent.com/22820318/167296188-cc62c82d-e575-46e2-9058-d53b46e2e456.png">

**Comment by hirbod** [comment]
I am not using StatusBar, since I am relying on react native screens automatic status bar manager which will break when using StatusBar or expo-status-bar. I am using expos integrated way of handling status bar on app launch through splash screen (expo.androidStatusbar.transparent)

**Comment by kirillzyusko** [comment]
@hirbod aha, got it. Will try to see how they manage it and why it's getting broken when it's used together with `KeyboardProvider`

BTW what are benefits of using RNS/Expo over StatusBar from RN?

**Comment by kirillzyusko** [comment]
@hirbod also I'm looking at https://reactnavigation.org/docs/native-stack-navigator/ and can not find `statusBarTranslucent` property... Do I correctly understand that you specify transparent status bar only by SplashScreen from Expo?

**Comment by hirbod** [comment]
I added the config via expo app.config.ts 

https://docs.expo.dev/guides/configuring-statusbar/

**Comment by hirbod** [comment]
Benefits are that react native screens has an automatic status bar handling integrated.

**Comment by Noitidart** [comment]
@hirbod side question - do you have steps on how you installed this lib into expo? did you write a config plugin for it?

**Comment by hirbod** [comment]
You don't need a config plug-in. Just a custom dev client. Install works ootb

**Comment by kirillzyusko** [comment]
@hirbod I will try to create expo app and will see why status bar is broken 👀

**Comment by kirillzyusko** [comment]
@Noitidart if non-ejected expo app is not supporting this library and it's possible to make it supporting (via config?), then could you open an issue and suggest how to create config (maybe some good examples of other open-source libraries not managed by expo team)?

**Comment by hirbod** [comment]
You don't need to "eject" (aka going bare). But you will need to install `expo-dev-client` and generate a custom dev client with EAS or Xcode/Android Studio, but you can also build in the cloud for free with EAS. No config plugins are required. 

You just can't use Expo Go, because for that, the native code by this library has to be included, which Expo won't do anymore, since custom dev clients are very easy to setup and super convenient (+ 50% smaller app size)

**Comment by hirbod** [comment]
@kirillzyusko you want me to setup a repo for you?

**Comment by hirbod** [comment]
@kirillzyusko here is the mcve.

https://github.com/hirbod/keyboard-controller-statusbar-issue-repro

- clone
- npm install -g expo-cli
- yarn
- expo run:android

I could reproduce the issue. It only happens with @react-navigation/native-stack and react-native-screens

**Comment by kirillzyusko** [comment]
@hirbod thanks, I will try to have a look tomorrow! And thanks for introduction into expo workflows. I haven't used expo almost for a year and it seems like a lot of things have changed :)

**Comment by hirbod** [comment]
A lot. Expo got just beautiful, specially since custom code is possible in a semi-managed workflow - which is just great.
I found out that `react-native-screens` has a prop `statusBarTranslucent` which does work with your KeyboardProvider, unfortunately it still has not been ported to react-navigation/native-stack.

I asked satya164 if anything speaks agains porting it. But would still be nice to workaround this anyway.

**Comment by kirillzyusko** [comment]
@hirbod nice, but anyway I'll try to figure out as well what's breaking status bar behaviour in my code 👍 Thanks for the repo again!

**Comment by Noitidart** [comment]
Amazing amazing thank you @kirillzyusko and @hirbod !

**Comment by kirillzyusko** [comment]
@hirbod which device/android emulator did you use? I'm testing on Pixel 3a API 32 (emulator) and it seems like everything works as expected:

<img width="205" alt="image" src="https://user-images.githubusercontent.com/22820318/167577374-59473be1-a14d-425c-8648-e1f5a394d230.png">

**Comment by hirbod** [comment]
I am using a real device, Redmi Note 8 Pro, Android 10

**Comment by kirillzyusko** [comment]
@hirbod okay, will try to run on my Redmi Note 5 Pro :)

**Comment by hirbod** [comment]
My device has a notch, this might also be a thing

**Comment by kirillzyusko** [comment]
@hirbod aha, good point, will check it as well 👍

**Comment by kirillzyusko** [comment]
@hirbod may I also ask you to upload a screenshot of how it looks on your device?

**Comment by hirbod** [comment]
![image](https://user-images.githubusercontent.com/504909/167594330-47abc5a6-eb69-44df-9024-b159d07d0816.jpeg)

![image](https://user-images.githubusercontent.com/504909/167594365-68cd495a-ac0d-45ca-b181-a74e22926491.jpeg)

**Comment by hirbod** [comment]
I also created a PR here to circumvent the issue in the feature with an easy `statusBarTranslucent` prop:
https://github.com/react-navigation/react-navigation/pull/10578

**Comment by kirillzyusko** [comment]
@hirbod I could reproduce the issue on my Xiaomi device. Using version from [PR](https://github.com/kirillzyusko/react-native-keyboard-controller/pull/15) and adding `statusBarTranslucent` to Provider fixes the problem 😊 Could you check it, please? If you confirm it, then I will merge and publish a new version of the library.
