### ISSUE TITLE
update example to use reanimated 3.

### ISSUE THREAD

**Issue by a-eid** [kirillzyusko/react-native-keyboard-controller#196]
example currently use reanimated 2, any change you could upgrade it to use the latest version of reanimated ?

**Comment by a-eid** [comment]
@kirillzyusko 

I was testing the library with a project that I recently upgraded to RNR 3.4.1, I was trying to copy some code by I faced some type mismatches because of reanimated version. 

- yes I'm using expo. ( managed workflow with dev client ).
- 3.3.0 and 3.4.1

**Comment by kirillzyusko** [comment]
@a-eid you had only types mismatches? Could you share example of mismatches?

I'm curious because I just reuse reanimated types, so there shouldn't be any conflict 🤔
