### ISSUE TITLE
[bug]: Exception in HostFunction: Value is undefined, expected a number

### ISSUE THREAD

**Issue by devoren** [kirillzyusko/react-native-keyboard-controller#197]
**Describe the bug**
I just want to run example app and only when i want to try `KeyboardAwareScrollView` i have this issue:

**Code snippet**
`KeyboardAwareScrollView`  from `Examples/KeyboardAwareScrollView`

**Repo for reproducing**
I would be highly appreciate if you can provide repository for reproducing your issue. It can significantly reduce the time for discovering and fixing the problem.

**To Reproduce**
1. Go to 'src/screens/Examples/'
2. yarn android

**Expected behavior**
This screenshot from version where had `onContentTouch` 
![Screenshot_1691337041](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/99968085/ae1d871b-1553-4c48-90c1-ede5872dcc7b)

**Screenshots**
After 1.5.8
![Screenshot_1691336860](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/99968085/77f5c0c4-2351-4b87-89cf-6e65b83e1bf8)

**Smartphone (please complete the following information):**
 - Desktop OS: [Windows 10]
 - Device: [Android Emulator]
 - OS: [Android 12]
 - RN version: [ 0.71.11]
 - RN architecture: [old]
 - JS engine: [Hermes]
 - Library version: [^1.5.8]

**Additional context**
When I run the example in version 1.5.7 or earlier, it runs without issue. I don't know, am I missing something, or am I not running the example as expected, or is there something really wrong? I haven't tried it on v3 yet

**Comment by kirillzyusko** [comment]
@devoren are you running example project using 1.5.8? Could you elaborate a little bit more about your setup? Did you add 1.5.8 into your own project and trying to run KeyboardAwareScrollView from example project?

Right now KeyboardAwareScrollView depends on new functionality which is available in `main` branch, but hasn't been published to `npm` yet. Maybe it's the problem?

**Comment by devoren** [comment]
> Right now KeyboardAwareScrollView depends on new functionality which is available in main branch, but hasn't been published to npm yet. Maybe it's the problem?

Hi @kirillzyusko Thank you for very quick reply! I think so. Maybe im silly, but i just download as zip and ran the example.
1.5.7 KeyboardAwareScrollView example:
https://github.com/kirillzyusko/react-native-keyboard-controller/assets/99968085/4b8d5cf1-2c8c-4559-bada-c15e25be173b

**Comment by devoren** [comment]
@kirillzyusko  While you're here, can I ask you one more thing? I don't understand this behaviour:

1. If I press the last input and scroll up, then when I close the keyboard it scrolls down (even if I press the first input before closing)
2. But if I press the first input and scroll down, it doesn't scroll back up again

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/99968085/3e55bd4e-91e5-47bc-bc3c-fbc1b3326ea1

**Comment by kirillzyusko** [comment]
So if you are running 1.5.8 - it doesn't work, but 1.5.7 works?
Are you using git tags? Because version in `main` is not equal to `1.5.8` and version from `main` is not compatible with `1.5.8`, since it's using new API.

> If I press the last input and scroll up, then when I close the keyboard it scrolls down (even if I press the first input before closing)
But if I press the first input and scroll down, it doesn't scroll back up again

I think it's a bug and I think @IvanIhnatsiuk told me about this problem too. In fact there is a quite simple math in this component, you can try to debug and understand when you need to prevent scroll etc.

I'm currently working on new `1.6.0` version, which will have some improvements, so for now I'll postpone debugging/fixing this problem because it can be automatically fixed with new changes.

BTW @IvanIhnatsiuk did you find a solution for this problem?👀

**Comment by devoren** [comment]
@kirillzyusko Oh, you're right, this whole problem was due to me downloading with `main` instead of `1.5.8` tag and just messing it up. Thank You for this awesome library! ❤️

**Comment by IvanIhnatsiuk** [comment]
@kirillzyusko No, I haven't found a solution to this problem yet, but I have some thoughts on how this can be fixed. So, I will have a look for a fix in the next few days 🙂
