### ISSUE TITLE
ease migration

### ISSUE THREAD

**Issue by gaultierq** [kirillzyusko/react-native-keyboard-controller#198]
This lib looks very promising ! Thanks for tackling this live long problem

One drawback imo, I find it difficult to start using it in a large app, relying heavily on different keyboard avoiding views / scroll views.
I found this repo when I needed to animate my modal size. On android I was missing an keyboard event, making it difficult to calculate the available space for my modal.
Opting in this lib gave me the missing event I needed, but also breaks every other keyboard avoiding screens.

I tried to using only `KeyboardEvents`, but it doesn't work without the `KeyboardProvider` context.

I also tried nesting only my modal with the context, and it works once, but once my modal has been displayed, other keyboard avoiding views are not working anymore.

My question is: can we "activate" react-native-keyboard-controller only for some views / screens ? activate it on demand ?

**Comment by kirillzyusko** [comment]
Hello @gaultierq 

I thought about adding `.setEnabled(boolean)` method, but didn't have time for investigation of how it can work/which new issues it can add 🤷‍♂️ 

Right now when you wrap your app in `KeyboardProvider` app starts to behave in the same way as iOS does - it doesn't resize the screen automatically and delegate control fully to you.

If you were relying on `adjustResize`/`adjustPan` behavior, then as a temporary solution you can write your own component that will mimicrate default Android behavior:

```tsx
const AndroidKeyboardResize = ({children}) => {
  const fullHeightRef = useRef(0);
  const [height, setHeight] = useState<undefined | number>(undefined);

  const onLayout = useCallback(({nativeEvent}) => {
    // save view size on component mount
    if (fullHeightRef.current === 0) {
      fullHeightRef.current = nativeEvent.height;
    }
  });

  useEffect(() => {
    const show = KeyboardEvents.addListener("keyboardWillShow", (e) => {
      if (Platform.OS === 'android') {
        // resize screen
        setHeight(fullHeightRef.current - e.height)
      }
    });
    const hide = KeyboardEvents.addListener("keyboardWillHide", (e) => {
      if (Platform.OS === 'android') {
        // restore full height
        setHeight(undefined);
      }
    });
  
    return () => {
      hide.remove();
      show.remove();
    };
  }, []);

  return (
    <View onLayout={onLayout} style={{height}}>
      {children}
    </View>
  );
};
```

Not sure this code works, but I think you can get the idea 😄 And of course let me know what do you think about it 😊

**Comment by cwhenderson20** [comment]
I want to echo @gaultierq here and say thank you so much for this library! It definitely helps solve one of the biggest problems when using React Native.

That being said, I'll register my +1 for "migration path" like enabling the behavior it affords only on certain screens. It's also quite possible I missed a key part of the documentation, but this wasn't initially obvious to me:

> Keyboardprovider moves app to edge-to-edge [mode](https://kirillzyusko.github.io/react-native-keyboard-controller/docs/recipes/platform-differences#android) and once it's done adjustPan/adjustResize will not have any effect on your app anymore

…so I spent some time wondering why my many other views stopped responding to keyboard events on Android.

**Comment by kirillzyusko** [comment]
Hello @cwhenderson20 

I've started a work here https://github.com/kirillzyusko/react-native-keyboard-controller/pull/227 but changed priority for now. Definitely I'll get back to this PR once I have more time!

If you have a desire - you can continue an implementation from where I left and if it works as expected I'll be happy to merge it 🙂 

In a meantime - do you think documentation can be somehow improved? I mean maybe I should add this information somewhere? If yes, then what is the page?

> Keyboardprovider moves app to edge-to-edge [mode](https://kirillzyusko.github.io/react-native-keyboard-controller/docs/recipes/platform-differences#android) and once it's done adjustPan/adjustResize will not have any effect on your app anymore

**Comment by gaultierq** [comment]
Thanks for your snippet  @kirillzyusko, I have used it in combination with a custom react context, and it was enough to activate / deactivate resizing behavior per screen. Great ! #227 and handling all that logic on the native side sounds promising. 

I'll let you close the issue if you think it's not useful anymore. 

FYI, I stumble upon `react-native-keyboard-controller` by looking for a way to subscribe to `keyboardWillHide` events on android. Adding `react-native-keyboard-controller` to my project took a lot more time than expected, but it was definitely worth it. Well done !

**Comment by kirillzyusko** [comment]
@gaultierq thank you for your answer! I'll keep this issue open for now and will close once https://github.com/kirillzyusko/react-native-keyboard-controller/pull/227 will be merged! Thank you for opening this issue!

And yes, I'm glad you found this library helpful!
