### ISSUE TITLE
build crashes when building for web

### ISSUE THREAD

**Issue by viljark** [kirillzyusko/react-native-keyboard-controller#208]
**Describe the bug**

Importing and using any dependency from 'react-native-keyboard-controller' will crash the build when building for web (react-native-web) with error:
`Unable to resolve "../Utilities/Platform" from "node_modules/react-native/Libraries/ReactNative/PaperUIManager.js"`

**Code snippet**
`import { KeyboardProvider } from 'react-native-keyboard-controller'`

```
 <KeyboardProvider>
  <View/>
 </KeyboardProvider>
```

**Repo**
https://snack.expo.dev/@viljarremato/hot-raisins

**To Reproduce**
import and use any dependency:
`import { KeyboardProvider } from 'react-native-keyboard-controller'`
```
 <KeyboardProvider>
  <View/>
 </KeyboardProvider>
```
run the expo web (RN web) project
`run expo start --web`

**Expected behavior**
Web bundle builds

**Smartphone (please complete the following information):**
 - Desktop OS: MacOs 13.0
 - RN version: 0.71.8
 - RN architecture: old
 - JS engine: Hermes
 - Library version: 1.5.7
 - Expo SDK 48

**Additional context**
I don't expect the package to work at all in web, but maybe it is possible to stub the library for web so that it would not crash.

**Comment by kirillzyusko** [comment]
Hello @viljark 

Yes, it makes sense what are you saying. I also agree with you that at least this lib shouldn't crash on web - I'll look into the problem! 👍

**Comment by kirillzyusko** [comment]
@viljark could you test, that https://github.com/kirillzyusko/react-native-keyboard-controller/pull/210 fixes the problem?

you can install it like:

```json
"react-native-keyboard-controller": "https://github.com/kirillzyusko/react-native-keyboard-controller#refactor/web-mock",
```

It works on my machine:

<img width="1023" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/61773970-0f34-4f02-8ed5-e5eaf8f7d896">
