### ISSUE TITLE
[Help] KeyboardAwareScrollview example not scroll to focused textInput

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [kirillzyusko/react-native-keyboard-controller#213]
**Describe the bug**
Please take a look for my repo to testing the KeyboardAwareScrollview example. the issue is it not scroll to focused textInput

**Code snippet**
KeyboardAwareScrollview copied from v1.5.8 Example
(https://github.com/kirillzyusko/react-native-keyboard-controller/blob/1.5.8/example/src/screens/Examples/AwareScrollView/KeyboardAwareScrollView.tsx)

**Repo for reproducing**
https://github.com/NguyenHoangMinhkkkk/testkeyboard

android windowSoftInputMode `android:windowSoftInputMode="adjustResize"`
```
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-keyboard-controller": "^1.5.8",
    "react-native-reanimated": "^3.4.2"
  },
```

**To Reproduce**
- input your number of TextInputs rendering on scrollview.
- Run Project. focus on TextInput at very bottom of scrollview -> keyboard shown -> the TextInput focused not scroll up, just staying behide keyboard

**Smartphone (please complete the following information):**
 - Device:  
**IOS** Simulator iPhone 14 - ios 16.4
**Android** pixel 3a. Android version 11

**Comment by kirillzyusko** [comment]
@NguyenHoangMinhkkkk does it happen because you didn't wrap your app in `KeyboardProvider`?
Or at least I can not see usage of provider in your app...
