### ISSUE TITLE
Animation support

### ISSUE THREAD

**Issue by koj-qq** [kirillzyusko/react-native-keyboard-controller#223]
thanks a lot for your work 
I have encountered a problem and need your help. I have added a setAnimeteHeight method in ios, but it has no animation. I look forward to your help

in KeyboardControllerViewManager.swift
@objc func setAnimeteHeight(_ height: NSNumber) {
    onEvent(event: "onKeyboardMoveStart", height: height, progress: 1)
  }

**Comment by kirillzyusko** [comment]
@koj-qq would you mind to explain in a little bit more details what you are trying to achieve and why do you need to modify swift code?

**Comment by kirillzyusko** [comment]
Closed due to inactivity and a lack of information.
