### ISSUE TITLE
need help about switch to customkeyboard(like telegram)

### ISSUE THREAD

**Issue by fukemy** [kirillzyusko/react-native-keyboard-controller#226]
Hi, to continue the issue here https://github.com/kirillzyusko/react-native-keyboard-controller/issues/131, I make a example to explain my problem

I describe my problem again:
`In Android(aka my options), switch to custom keyboard always make jump layout and not smooth like telegram, like my video below`:

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/8202437/38aced64-89da-45b4-ace0-8df0292fd5aa

Here is my sample code:( I edit in ReAnimatedChat folder => ***index.tsx***):
```
import React, { useEffect, useRef, useState } from 'react';
import { Keyboard, Text, TextInput, View } from 'react-native';
import { KeyboardEvents, useReanimatedKeyboardAnimation } from 'react-native-keyboard-controller';
import Reanimated, {
  useAnimatedStyle,
  useDerivedValue,
} from 'react-native-reanimated';

import Message from '../../../components/Message';
import { history } from '../../../components/Message/data';
import { useTelegramTransitions } from './hooks';
import styles from './styles';

import type { StackScreenProps } from '@react-navigation/stack';
import type { ExamplesStackParamList } from '../../../navigation/ExamplesStack';

const AnimatedTextInput = Reanimated.createAnimatedComponent(TextInput);

type Props = StackScreenProps<ExamplesStackParamList>;

function ReanimatedChat({ navigation }: Props) {
  const [showCustomKeyboard, setShowCustomKeyboard] = useState(false);
  const keyboardHeightRef = useRef<number>(270)//defaut sticker keyboard height

  useEffect(() => {
    const subscription = KeyboardEvents.addListener('keyboardWillShow', (e) => {
      keyboardHeightRef.current = e.height
    });

    return () => subscription.remove();
  }, []);

  useEffect(() => {
    navigation.setOptions({
      headerRight: () => (
        <Text
          style={styles.header}
          onPress={() => setShowCustomKeyboard((value) => !value)}>
          {`sticker keyboard: ${showCustomKeyboard ? 'On' : 'Off'}`}
        </Text>
      ),
    });
  }, [showCustomKeyboard]);

  const { height: platform } = useReanimatedKeyboardAnimation();
  const height = useDerivedValue(
    () => platform.value,
    []
  );

  const scrollViewStyle = useAnimatedStyle(
    () => ({
      transform: [{ translateY: height.value }, ...styles.inverted.transform],
    }),
    []
  );
  const textInputStyle = useAnimatedStyle(
    () => ({
      height: 50,
      borderRadius: 12,
      marginHorizontal: 12,
      borderColor: 'green',
      borderWidth: 1,
      backgroundColor: '#BCBCBC',
      transform: [{ translateY: height.value }],
    }),
    []
  );

  const customStickerStyle = useAnimatedStyle(
    () => ({
      height: showCustomKeyboard ? keyboardHeightRef.current : 0
    })
  )
  const fakeView = useAnimatedStyle(
    () => ({
      height: Math.abs(height.value),
    }),
    []
  );

  return (
    <View style={styles.container}>
      <Reanimated.ScrollView
        showsVerticalScrollIndicator={false}
        style={scrollViewStyle}>
        <View style={styles.inverted}>
          <Reanimated.View style={fakeView} />
          {history.map((message, index) => (
            <Message key={index} {...message} />
          ))}
        </View>
      </Reanimated.ScrollView>
      <AnimatedTextInput style={textInputStyle} />
      <Reanimated.View style={[{
        width: '100%',
        backgroundColor: 'red'
      }, customStickerStyle]}/>
    </View>
  );
}

export default ReanimatedChat;
```
As your mention here: https://github.com/kirillzyusko/react-native-keyboard-controller/issues/131#issuecomment-1693539226

 You said `When keyboard changes its size the library makes an animated transition`, I agree because it's work good when change the `system emoji keyboard`, but I want to implement my custom keyboard, it's act like my above video.
 
  Can you give me some advices? Thanks

**Comment by kirillzyusko** [comment]
Hello @fukemy 

Jump happens here:

```tsx
const customStickerStyle = useAnimatedStyle(
    () => ({
      height: showCustomKeyboard ? keyboardHeightRef.current : 0
    })
  )
```

You are instantly trying to change a height of one view from `0` to `keyboardHeight`. Try to consider using (though I'm not sure, that `withTiming` will work in `useAnimatedStyle`, but I think you get the idea).

```tsx
const customStickerStyle = useAnimatedStyle(
    () => ({
      height:  withTiming(showCustomKeyboard ?keyboardHeightRef.current) : 0).value
    })
  )
```

Also you are keeping two independent values for managing keyboard height (system and sticker) - because of that you have a double space. Telegram typically close the keyboard and just keep sticker space.

You may find [useKeyboardHandler](https://kirillzyusko.github.io/react-native-keyboard-controller/docs/api/hooks/use-keyboard-handler) hook interesting, because it gives an access to keyboard lifecycle. In your case you can easily intercept the moment when you press on a button and when you need to ignore values reported by system keyboard movement.

Let me know if you have any other question (but please, be more specific - the code that you provided works absolutely as expected. Based on the issue I don't understand the expected result - is it expected to work as in Telegram app? If so, then your code contains a lot of mistakes that leads to the behavior that you currently see).

**Comment by fukemy** [comment]
I tried 2 days by following your guide but no luck to me, I can not solve the jump state when changing keyboard, I close the issue now due to no solution

**Comment by kirillzyusko** [comment]
@fukemy Just try to log more values and you'll understand where your code doesn't work as expected. Also you may try to use https://github.com/wix-incubator/react-native-keyboard-input - theoretically it will replace a content of system keyboard and transitions will be smooth out of the box.

**Comment by kirillzyusko** [comment]
Linked issue - https://github.com/kirillzyusko/react-native-keyboard-controller/issues/226

There I give a code sample on how to achieve a desired behavior.
