### ISSUE TITLE
Change AndroidSoftInputMode has no effect

### ISSUE THREAD

**Issue by dayze** [kirillzyusko/react-native-keyboard-controller#233]
**Describe the bug**
When changing the AndroidSoftInputMode, neither `SOFT_INPUT_ADJUST_PAN` or `SOFT_INPUT_ADJUST_RESIZE` works

**Code snippet**
```
export default function ScreenExample({ navigation }: Props) {
  useEffect(() => {
    KeyboardController.setInputMode(
      AndroidSoftInputModes.SOFT_INPUT_ADJUST_PAN
    );
  }, []);

  return (
    <View style={{ flex: 1 }}>
      <View style={styles.inner}>
        <Text style={styles.heading}>Header</Text>
        <View>
          <TextInput
            placeholder="Username"
            placeholderTextColor="#7C7C7C"
            style={styles.textInput}
          />
          <TextInput
            placeholder="Password"
            placeholderTextColor="#7C7C7C"
            style={styles.textInput}
          />
        </View>
        <TouchableOpacity style={styles.button}>
          <Text style={styles.text}>Submit</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}
```

**Screenshots**

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/11976270/9184aeb0-3e2c-40a1-8ea3-5336df19f232

**Smartphone (please complete the following information):**
 - Device: redmi pro 8
 - Library version: 1.7.0

**Comment by kirillzyusko** [comment]
Hello @dayze 

Actually it works. The thing is that once you've entered `edge-to-edge` mode - all resizing stuff will not be applied. I. e. if you wrapped app inside `KeyboardProvider` - app will behave like iOS does and will not resize the window on its own.

You can read more explanation in this issue - https://github.com/kirillzyusko/react-native-keyboard-controller/issues/198

I'm currently working on a solution in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/227 which gives you an ability to fallback to default resizes mechanism on demand.

Let me know if you have further questions or if you think that documentation should be somehow improved to make it more explicit 👀

**Comment by dayze** [comment]
Hello @kirillzyusko, thanks for the library btw 👌
 
Crystal clear thanks, waiting for the `enabled` feature to integrate inside android apps
