### ISSUE TITLE
KeyboardProvider with react-navigation-bottom-tabs

### ISSUE THREAD

**Issue by devoren** [kirillzyusko/react-native-keyboard-controller#241]
**Describe the bug**
I have KeyboardProvider in my root layout(i use expo router). If i switch between tabs first time it jumps and flickers

**Code snippet**
```
<KeyboardProvider>
	<BottomSheetModalProvider>
		<SafeAreaProvider>
		<Stack
			initialRouteName="(tabs)"
			screenOptions={{
				headerShadowVisible: false,
				header: (props) => <Header {...props} />,
			}}>
			<Stack.Screen name="(tabs)" options={{ headerShown: false }} />
		</Stack>
		</SafeAreaProvider>
	</BottomSheetModalProvider>
</KeyboardProvider>
```

**Repo for reproducing**
I would be highly appreciate if you can provide repository for reproducing your issue. It can significantly reduce the time for discovering and fixing the problem.

**To Reproduce**
1. Create app with bottom tabs
2. Add keyboardprovider
3. Switch between tabs
4. See this behavior

**Expected behavior**
If i remove KeyboardProvider it works fine. It must switch without flickers or jump

**Screenshots**
with provider:

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/99968085/df101d0f-7b6f-49a2-9bcc-44011d84455d

without provider:

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/99968085/43f6729e-ac11-4e13-ae35-5af718a12dd2

**Smartphone (please complete the following information):**
 - Desktop OS: [e.g. Windows 10]
 - Device: [Emulator]
 - OS: [12]
 - RN version: [72.4]
 - RN architecture: [old]
 - JS engine: [Hermes]
 - Library version: [1.7.0]

**Additional context**

**Comment by devoren** [comment]
Also with Provider the bottom tabs are rendered slower.

**Comment by kirillzyusko** [comment]
Hello @devoren 👋 

Did you try to put `KeyboardProvider` under `SafeAreaProvider`?

**Comment by devoren** [comment]
@kirillzyusko Hey!!! yes i tried but it did not help, im gonna create repo then you can check if you have free time

**Comment by kirillzyusko** [comment]
@devoren yes, sure, please do! It'll help me a lot during the investigation!

**Comment by devoren** [comment]
@kirillzyusko https://github.com/devoren/reposdk49 hope it helps!

**Comment by kirillzyusko** [comment]
@devoren just a minor update from my side. I dig down just a little, but from my initial observation - the problem is somewhere between `edge-to-edge` mode (I commented out `goToEdgeToEdge` implementation) and `react-navigation` header layout calculation.

In our app such jump doesn't occur, because we disable a header on top level of navigator and use only headers that are associated with current screen, so in your case it looks like (no jumps):

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/f5d9eaa6-4453-4ac1-b95a-bc22b4805179

The case that you described is really interesting and I'm going to dig deeper into `react-navigation` code to see why such jump occurs and what is the conflict with `edge-to-edge` mode 👍

**Comment by kirillzyusko** [comment]
@devoren this is all code modifications that I made:

<img width="683" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/3383a0e6-e64c-483d-b7a4-92d2dbdfaef6">
<img width="517" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/2fb496b9-9ad8-4d65-b765-9f51702a1518">
<img width="834" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/97a7e081-43c7-4a4d-b62e-f23ebbd6cf66">
<img width="829" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/f5a53b97-5f28-47db-8efe-b14b01d7e8a0">

I think I disabled header of each screen and enabled header for TabBar (which I believe not a desired behavior). Anyway, I'm going to experiment in nearest days and see what's wrong there. Layout in our app is similar to yours and we don't experience this problem 🤷‍♂️

**Comment by devoren** [comment]
@kirillzyusko :( i dont know my app jumps like that, do you use expo-router or react-navigation?

**Comment by kirillzyusko** [comment]
@devoren we're using `react-navigation` (but I don't think it's a problem, because expo-router is just a wrapper over `react-navigation`). I will also try to add an example in example app and see whether it's reproducible there or not 👀

**Comment by devoren** [comment]
@dayze  :(((, it didnt help, now bottom tabs jumps onload and when switch it goes to down to default position 😢

**Comment by dayze** [comment]
@devoren it really is just a quick fix that works on my project (without expo), there is something deeper here

```
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import * as React from 'react';
import {Text, View} from 'react-native';
import {KeyboardProvider} from 'react-native-keyboard-controller';
import {SafeAreaView} from 'react-native-safe-area-context';

const Stack = createNativeStackNavigator();
const Tab = createBottomTabNavigator();

function HomeScreen() {
  return (
    <View
      style={{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      }}>
      <Text>Home!</Text>
    </View>
  );
}

function SettingsScreen() {
  return (
    <View
      style={{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      }}>
      <Text>Settings!</Text>
    </View>
  );
}

const BottomTabs = () => {
  return (
    <SafeAreaView edges={['bottom']} style={{flex: 1}}>
      <Tab.Navigator>
        <Tab.Screen
          options={{headerShown: false}}
          name="Home"
          component={HomeScreen}
        />
        <Tab.Screen
          options={{headerShown: false}}
          name="Settings"
          component={SettingsScreen}
        />
      </Tab.Navigator>
    </SafeAreaView>
  );
};

function App() {
  return (
    <KeyboardProvider navigationBarTranslucent statusBarTranslucent>
      <NavigationContainer>
        <Stack.Navigator screenOptions={{headerShown: false}}>
          <Stack.Screen name="BottomTabs" component={BottomTabs} />
        </Stack.Navigator>
      </NavigationContainer>
    </KeyboardProvider>
  );
}

export default App;
```

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/11976270/0e81ec32-801e-4013-a95c-fba757f44340

**Comment by kirillzyusko** [comment]
@dayze from my observation jump happens somewhere inside of header (the layout is changed after a mount), but in your example headers are hidden 🤔

**Comment by devoren** [comment]
yes you are right with header it does not work:(

**Comment by devoren** [comment]
i use native-stack (expo-router uses it as default stack), Maybe there is a problem in the native stack?

**Comment by kirillzyusko** [comment]
> i use native-stack (expo-router uses it as default stack), Maybe there is a problem in the native stack?

Yes, definitely. I thought that we are using `native-stack` in certain places, but it turned out that we use only js `stack` everywhere 😲 That's why everything works fine in our app.

I've tried to switch to js `stack` in your example and it also started to work fine 🙂 

I digged into native-stack implementation. I found that [headerHeight](https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/views/NativeStackView.native.tsx#L231) switches from `59` to `97.14285659790039`. It happens because of values from `useSafeAreaInsets` hook.

Even if specify hardcode values for [useSafeAreaInsets](https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/views/NativeStackView.native.tsx#L202):

```diff
-const insets = useSafeAreaInsets();
+const insets = {"bottom": 0, "left": 0, "right": 0, "top": 41.14285659790039};
```

The jump in header still occur (though it's less visible): 

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/90e5e8ce-4b6f-4ca5-beac-707b680f4080

I'll continue an investigation - right now it's not very clear why these jumps happens.

**Comment by anieve01** [comment]
@kirillzyusko I'm unfortunately experiencing this exact issue also at my company. And my team has spent countless hours trying to resolve this to no avail. 

I just noticed this thread and I really appreciate seeing that you're on top on this. My team is using expo-router just like @devoren is. 

Thanks for looking into this and being so responsive. We're really hoping that you figure out a solution!

**Comment by mrtawil** [comment]
Same problem is happening to me when using `Share.share` from react native

**Comment by kirillzyusko** [comment]
@mrtawil whenever you call `Share.share` jump at header occurs? Or in specific configuration with bottom tabs or any other configuration?

**Comment by devoren** [comment]
https://github.com/react-navigation/react-navigation/issues/11372
https://github.com/react-navigation/react-navigation/issues/11285
Are these questions related to the current problem?

**Comment by mrtawil** [comment]
@kirillzyusko I tried to do the following with another package on a new project:

react-native: 0.72.4
react-native-reanimated: 3.5.4
react-native-safe-area-context: 4.7.2

The code is:
```
import React, { useEffect } from "react";
import { Button, Keyboard, Share, Text, TextInput, View } from "react-native";
import Animated, { useAnimatedKeyboard, useAnimatedStyle } from "react-native-reanimated";
import { SafeAreaProvider, useSafeAreaInsets } from "react-native-safe-area-context";

const App = () => {
  const { height } = useAnimatedKeyboard();

  const textInputContainerStyle = useAnimatedStyle(() => {
    return ({
      transform: [{ translateY: -height.value }],
    })
  });

  async function delay(milliseconds: number) {
    await new Promise(resolve => setTimeout(resolve, milliseconds));
  }

  const handleShare = async () => {
    const options = {
      title: 'Share React Native',
      message: 'React Native | A framework for building native apps using React',
    };

    console.log('before share');

    Share.share(options)
      .then(() => {
        console.log('then share');
      })
      .catch(() => {
        console.log('catch');
      });
  };

  return (
    <SafeAreaProvider>
      <View style={{ flex: 1, backgroundColor: 'green' }} onTouchStart={() => Keyboard.dismiss()}>
        <View style={{ position: 'absolute', top: 0, left: 0, width: '100%', zIndex: 9 }}>
          <Button title="Share" onPress={handleShare} />
        </View>
        <Animated.View
          style={[textInputContainerStyle, {
            flex: 1,
          }]}>
          <View style={{ position: 'absolute', bottom: 150, alignSelf: 'center' }}>
            <Text style={{ color: 'white', fontSize: 18, fontWeight: '700' }}>Share Demo</Text>
          </View>
          <TextInput
            blurOnSubmit={true}
            style={{
              position: 'absolute',
              bottom: 0,
              left: 0,
              backgroundColor: 'white',
              width: '100%',
            }}
            placeholder="type a message"
          />
        </Animated.View>
      </View>
      <Home />
    </SafeAreaProvider>
  )
};

const Home = () => {
  const insets = useSafeAreaInsets();

  useEffect(() => {
    console.log({ insets });
  }, [insets]);

  return (
    <></>
  );
};

export default App;
```

The result is:
When I call `Share.share` insets value changes, once it adds the status bar height to the top, and then it adds some number to the bottom. Then it goes back to zero. Knowing that I am not using a translucent status bar or did any change in the Android configuration.

```
 LOG  {"insets": {"bottom": 0, "left": 0, "right": 0, "top": 0}}
 LOG  before share
 LOG  then share
 LOG  {"insets": {"bottom": 0, "left": 0, "right": 0, "top": 31.288888931274414}}
 LOG  {"insets": {"bottom": 14.933333396911621, "left": 0, "right": 0, "top": 0}}
 LOG  {"insets": {"bottom": 0, "left": 0, "right": 0, "top": 0}}
 ```
 
 Note: This only happened on a real device and not on the simulator. Samsung A52s

**Comment by devoren** [comment]
@kirillzyusko Hello!  with/without:

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/99968085/01b6f512-2de1-43ea-b94f-208fca377c32

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/99968085/60e975d0-94e7-49d5-aa13-c06e7baea6f6

**Comment by kirillzyusko** [comment]
@devoren in `withoutprovider` video jump still occurs (just for a fraction of second, but it occurs):

|Collapsed header|Header with proper size|
|-----------------|------------------------|
|<img width="485" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/f728afa6-ca5d-43dc-a062-943ea7e043a4">|<img width="486" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/d10ca053-0c0f-4d88-b05a-4eeea53e9b12">|

@mrtawil I see you are using reanimated 🤔 Anyway, if the same issue is reproducible with RNKC, please, create a separate issue 🙏

**Comment by mrtawil** [comment]
@kirillzyusko I have shared my example to give you more scope about what might be the cause of the problem.

The same scenario happens while using `react-native-keyboard-controller` and wrapping the components with `KeyboardProvider`.

**Comment by kirillzyusko** [comment]
@mrtawil got it. Anyway may I kindly ask you to create a separate issue?

Don't want to mix different problems in a single place.

**Comment by devoren** [comment]
> @devoren in `withoutprovider` video jump still occurs (just for a fraction of second, but it occurs):

Lol, i see... In my company's app, our initial tab stack doesn't have a header, so when we switch, we don't notice the header jump (or it does, but it's hard to notice). But the bottom tab is very annoying when it jumps. All my headaches are with the bottom tab 😢

**Comment by devoren** [comment]
Hello everyone! IDK HOW, but after upgrading to rn 0.72.5 bottom tab is not jumping? Maybe my build lagging? Can you  check if it works or my app is lagging??

**Comment by devoren** [comment]
Hello everyone! IDK HOW, but after upgrading to rn 0.72.5 bottom tab is not jumping? Maybe my build lagging? Can you check if it works or my app is lagging?? I delete all android build and node modules after upgrading expo and react native libraries but not expo-router or react navigation, idk how but my app is not jumping now

**Comment by anieve01** [comment]
@kirillzyusko  With react-native-keyboard-controller@^1.8.0 and an upgrade to RN 0.72.5, I also see the bottom-tabs jumping issue resolved as @devoren mentioned. Still testing to ensure that the fix is stable and consistent. 

If you did something as part of that latest release to solve this, big thank you!

**Comment by kirillzyusko** [comment]
@devoren @anieve01 I think https://github.com/kirillzyusko/react-native-keyboard-controller/pull/227 resolved the problem.

In this PR I re-worked the way how I handle insets - now I don't use various hacks with async insets handling and do a correct consumption/insets propagation to child views.

And I also remember that at some point of time I've tested the repro provided in this issue with this PR and I didn't notice jumps in bottom tabs 😲.

So my idea was to release `1.8.0` because it contained some important fixes and then I wanted to test this issue again over weekend.

But you are saying everything works okay with `1.8.0`, right? Can I close this issue then?

**Comment by devoren** [comment]
@kirillzyusko Thank you ❤️
