### ISSUE TITLE
Deep linking into a backgrounded app causes NullPointerException dispatchDetachedFromWindow() called on a null object reference

### ISSUE THREAD

**Issue by thespacemanatee** [kirillzyusko/react-native-keyboard-controller#242]
**Describe the bug**

It's hard to reproduce this crash but I found an easy way. From the home screen launcher, trigger a deep link into your app by typing your App Link into the search bar.

Stacktrace:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchDetachedFromWindow()' on a null object reference
  android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3976)
  android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3976)
  android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3976)
  android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3976)
  android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:5563)
  android.view.ViewRootImpl.doDie(ViewRootImpl.java:8811)
  android.view.ViewRootImpl.die(ViewRootImpl.java:8787)
  android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:512)
  android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:453)
  android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:208)
  android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5670)
  android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
  android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
  android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
  android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
  android.os.Handler.dispatchMessage(Handler.java:106)
  android.os.Looper.loopOnce(Looper.java:205)
  android.os.Looper.loop(Looper.java:294)
  android.app.ActivityThread.main(ActivityThread.java:8177)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Code snippet**

```ts
const App = () => {
  return (
    <KeyboardProvider>
      <AppContent />
    </KeyboardProvider>
  )
}
```

**Repo for reproducing**

I'll create an example repo if the provided info is not sufficient because time is tight on my end.

**To Reproduce**
1. Wrap your app in a `KeyboardProvider` from RNKC
2. Open the app
3. Background it
4. Launch the app using a deep link or web link

**Expected behavior**

The app should come into the foreground instead of crashing

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 13
 - RN version: 0.72.4
 - RN architecture: Paper
 - JS engine: hermes
 - Library version: 1.7.0

**Comment by kirillzyusko** [comment]
Hello @thespacemanatee 👋 

May I kindly ask you to create a repo for reproduction or add a code snippet that I should paste into example app and which command do I need to run in order to reproduce the problem?

I think the crash happens in `onDetachedFromWindow` method, but it's better to reproduce a problem to understand why such exception occurs 🙏

**Comment by kirillzyusko** [comment]
@thespacemanatee but are you able to receive keyboard events using such patch? I think by using:

```ts
const KeyboardControllerView = View as unknown as React.FC<KeyboardControllerProps>;
```

You will use mock version of `KeyboardControllerView` which will not propagate events to JS. On Android it's taking `KeyboardControllerView` from `bindings.native.ts`. `bindings.ts` is serving as mock for other unsupported platforms 😐 

So if I understand everything correctly - on Android all hooks exported from this library will send default values and will not update these values when keyboard is moving.

**Comment by thespacemanatee** [comment]
@kirillzyusko thanks for the quick responses. The weird thing is that `KeyboardAvoidingView` still works with the patch above, but agree that it's probably the wrong patch.

I did some digging and the following patch fixes this:

```patch
diff --git a/node_modules/react-native-keyboard-controller/android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt b/node_modules/react-native-keyboard-controller/android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
index cb43bbe..1bb7027 100644
--- a/node_modules/react-native-keyboard-controller/android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
+++ b/node_modules/react-native-keyboard-controller/android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
@@ -13,7 +13,6 @@ import androidx.core.view.WindowInsetsCompat
 import com.facebook.react.uimanager.ThemedReactContext
 import com.facebook.react.views.view.ReactViewGroup
 import com.reactnativekeyboardcontroller.KeyboardAnimationCallback
-import com.reactnativekeyboardcontroller.extensions.removeSelf
 import com.reactnativekeyboardcontroller.extensions.requestApplyInsetsWhenAttached
 import com.reactnativekeyboardcontroller.extensions.rootView
 
@@ -63,7 +62,7 @@ class EdgeToEdgeReactViewGroup(private val reactContext: ThemedReactContext) : R
   override fun onDetachedFromWindow() {
     super.onDetachedFromWindow()
 
-    eventView.removeSelf()
+//    eventView.removeSelf()
   }
   // endregion
```

Looks like there's a bug with the `View.removeSelf` extension, maybe the null checks aren't sufficient. Will see if I can fix that but please look at it too when you have the time, thanks!

**Comment by thespacemanatee** [comment]
@kirillzyusko thanks for the quick responses. The weird thing is that KeyboardAvoidingView still works with the patch above, but agree that it's probably the wrong patch. I found the issue though, you need to postpone modifying the view hierarchy like so:

```patch
diff --git a/node_modules/react-native-keyboard-controller/android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt b/node_modules/react-native-keyboard-controller/android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
index cb43bbe..7cc7fb2 100644
--- a/node_modules/react-native-keyboard-controller/android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
+++ b/node_modules/react-native-keyboard-controller/android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
@@ -63,7 +63,7 @@ class EdgeToEdgeReactViewGroup(private val reactContext: ThemedReactContext) : R
   override fun onDetachedFromWindow() {
     super.onDetachedFromWindow()
 
-    eventView.removeSelf()
+    Handler(Looper.getMainLooper()).post { eventView.removeSelf() }
   }
   // endregion
```

I can create a PR?

**Comment by kirillzyusko** [comment]
@thespacemanatee yes, sure, go ahead! Just add a comment above `Handler(Looper.getMainLooper()).post { eventView.removeSelf() }` why it's needed and add a link to this issue (in this case I will be sure, that I'll not accidentally remove it during a refactoring).

And also would be good to add an example app (I'm currently working on e2e tests and want to cover as much as possible rare scenarios). So testing deeplinks is definitely a thing that I don't perform very often, so I think it would be good to automate as well.

Anyway looking forward to your PR! 😎

**Comment by kirillzyusko** [comment]
Hi @thespacemanatee 👋 

I added a draft integration with deep links, but still can not catch the exception 🤷‍♂️ 

My `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <uses-permission android:name="android.permission.INTERNET"/>
  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme" android:networkSecurityConfig="@xml/network_security_config">
    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustPan" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="rnkcexample"/>
      </intent-filter>
    </activity>
  </application>
</manifest>
```

My `App.tsx`:

```tsx
import 'react-native-gesture-handler';

import * as React from 'react';
import { ActivityIndicator, StyleSheet } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { KeyboardProvider } from 'react-native-keyboard-controller';
import {
  SafeAreaProvider,
  initialWindowMetrics,
} from 'react-native-safe-area-context';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import RootStack from './navigation/RootStack';

const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
});

const linking = {
  prefixes: ['rnkcexample://'],
  config: {
    initialRouteName: 'EXAMPLES_STACK',
    screens: {
      EXAMPLES_STACK: {
        path: 'examples',
        screens: {
          ANIMATED_EXAMPLE: {
            path: 'animated',
          },
        },
      },
    },
  },
};

export default function App() {
  return (
    <SafeAreaProvider initialMetrics={initialWindowMetrics}>
      <GestureHandlerRootView style={styles.root}>
        <KeyboardProvider statusBarTranslucent>
          <NavigationContainer
            linking={linking}
            fallback={<ActivityIndicator color="blue" size="large" />}
          >
            <RootStack />
          </NavigationContainer>
        </KeyboardProvider>
      </GestureHandlerRootView>
    </SafeAreaProvider>
  );
}
```

And I'm testing it like:

```shell
adb shell am start -W -a android.intent.action.VIEW -d "rnkcexample://examples/animated" com.example.reactnativekeyboardcontroller
```

Are you using `react-navigation`? 👀

**Comment by thespacemanatee** [comment]
@kirillzyusko hey thanks for investigating this. I haven't had the time to repro or create a PR as I have a day job, but what I can say is that I used Android App Links to repro this error. Perhaps you can register `https://example.com` in your intent-filters and manually enable it in App Info Open Supported Links. Then type in `example.com` in the homescreen Google search bar. Make sure the app is open in the background before trying!

**Comment by kirillzyusko** [comment]
Thanks @thespacemanatee 🙌 

I'm able to reproduce this problem! And I can confirm - your solution is not triggering a crash! I'll look for other solutions as well and I hope will create a PR with a fix soon (including example app for reproduction)!

**Comment by kirillzyusko** [comment]
Thank you @thespacemanatee for your contribution!

I'll publish it under `1.8.0` but first of all want to check some issues reported with interactive keyboard on iOS 17.

You can apply a patch locally via `patch-package` to overcome this issue (and I believe you already did it 😅).

**Comment by thespacemanatee** [comment]
@kirillzyusko indeed I have, so please take as much time as you need. Really amazing work with the library and also appreciate the quick turnaround times with the posted issues!
