### ISSUE TITLE
Need `StickyFooter` component

### ISSUE THREAD

**Issue by idrakimuhamad** [kirillzyusko/react-native-keyboard-controller#251]
I'd like to have something similar like `KeyboardAwareView` component but instead of making the whole layout aware, I only wanted a portion of the layout to be aware. For example something like comment input of FaceBook app, as Ive attached below.

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/1400323/404f9e59-f91f-465a-a077-90cd20a3fe7e

Essentially I want a component that sticks at the bottom of the screen, with a list on top it. And when the keyboard appears, it'd be positioned on top of the keyboard, while the list maintains its position. This is not achievable with `KeyboardAwareView`. It also requires to set a minHeight, where i need to take the whole space of the screen.

So the question if maybe I can still make use of `KeyboardAwareView` to do this or a custom implementation is needed? Thanks!

**Comment by kirillzyusko** [comment]
@idrakimuhamad can you try to wrap your `TextInput` in `KeyboardAvoidingView` (from this library) and specify `behavior="posiiton"` and then see how it behaves?

Basically me and @MarceloPrado are working on adding `StickyFooter` component as part of this library. You can check the basic implementation here https://github.com/kirillzyusko/react-native-keyboard-controller/pull/245 and also do some testing/give a feedback 🙌 

It will help us a lot!

**Comment by Dajust** [comment]
Try this

```js
const {height, progress} = useReanimatedKeyboardAnimation();
const insets = useSafeAreaInsets();
const footerStyle = useAnimatedStyle(
    () => ({
      height: 50,
      transform: [
        {
          translateY: height.value
            ? height.value + insets.bottom
            : height.value,
        },
      ],
    }),
    [],
  );```

**Comment by idrakimuhamad** [comment]
Yeah I actually already have similar solution to this Sticky Footer. However I notice some sort of bugs that only happens on certain Android phones of my QAs, notable Samsung S9 and Huawei. I couldn't replicate it in Emulator or some other samsung devices.

The issue I've noticed is that the `useReanimatedKeyboardAnimation` values are not getting the latest value, when the keyboard are dismissed through an unconventional way, eg tapping back button on header, pressing physical back button which triggered navigation go back.

When revisiting the same screen afterwards, the sticky footer floats as in the keyboard still appearing. When I logged the height and progress, it seems that the values are still from the previous render. If the input were focused, and close by tapping outside of keyboard, it will get update back.

Again, this doesn't happen on all devices, and iOS is fine. To create replication, I need to create new project first and actually use my testers phone to do so 😅 so might take some time

**Comment by idrakimuhamad** [comment]
> @idrakimuhamad do you use react-navigation or react-native-navigation? Which Android OS versions are buggy in your case?

We use expo-router, so I guess that's React-Navigation. One of it, if I'm not mistaken the Huawei is Android 10.

**Comment by kirillzyusko** [comment]
@idrakimuhamad I think such problem happens because component unmount happens faster than a keyboard gets dismissed. And if you are using default hooks - they will restore default `softInputMode` on unmount. And it can cause some troubles.

Can you try to follow this [guide](https://kirillzyusko.github.io/react-native-keyboard-controller/docs/guides/building-own-hook) and create your own version of hook? Just for experiment simplicity you can restore default mode on unmount as well, but you can add timeout, to be sure that keyboard gets closed first and only after that you change `softInputMode`.
If it works, then you can come up with a more sophisticated approach.
