### ISSUE TITLE
Proposal: Merge with react-native-bars project

### ISSUE THREAD

**Issue by zoontek** [kirillzyusko/react-native-keyboard-controller#259]
Hi 👋

First, thanks for your work on this library, this is very much needed in the ecosystem!

I'm currently maintaining [`react-native-bars`](https://github.com/zoontek/react-native-bars), a library for fully transparent (and fallback to translucent) system bars. Compared to `KeyboardProvider` `statusBarTranslucent` and `navigationBarTranslucent`, it provides an android theme that avoid the initial blink (before the React app kicks in) + provides some useful components to handle `barStyle` (similarly as the builtin `StatusBar` component).

As keyboard handling is super related to system bars, I think it could be great to merge those libs? (I even think that it should enforce fully transparent UI without any choice, exactly like `react-native-bars` or iOS + recommend `react-native-safe-area-context` for dealing with safe areas in a similar way on both OS, but it's my personal opinion 😅)

**Comment by kirillzyusko** [comment]
Hello @zoontek 👋 

I understand the motivation to merge these projects (because of native code in Android).

But I'm just thinking, that people who wants to control `NavigationBar` may not understand why do they need to install library that helps you to deal with keyboard? 🤔 What do you think about it?

**Comment by kirillzyusko** [comment]
Yes @zoontek it makes sense what you are saying! I just was confused about SEO search (obviously name `react-native-keyboard-controller` doesn't give a confidence that it's a right library for managing Navigation and System bar 😅).

In order to merge projects we need:
- to have `init` method for overriding a theme to avoid a blink;
- new NativeModule for managing NavigationBar and StatusBar properties;
- components in JS (NavigationBar, StatusBar).

Did I miss anything?

**Comment by zoontek** [comment]
@kirillzyusko I think there's no need for the `init` method in `react-native-keyboard-controller`, as setting a parent style (`Theme.EdgeToEdge) + waiting for `KeyboardProvider` to kicks in should do the job.

For the rest, that's it, yeah. Maybe I could experiment on a branch if you are OK with that?

**Comment by kirillzyusko** [comment]
@zoontek yes, sure, feel free to experiment with it 👍  😊

**Comment by zoontek** [comment]
I noticed something: `navigationBarTranslucent` currently doesn't seem to enable [edge-to-edge layout](https://developer.android.com/develop/ui/views/layout/edge-to-edge-manually).
Navigation bar stays dark and the UI is not drawn under:

<img width="508" alt="Screenshot 2023-12-10 at 13 37 42" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/1902323/f188d20b-bb61-4d4a-bc1d-4ea213858f02">

---

So, I enforce edge-to-edge like this:

```java
@Override
public void onCreate(Bundle savedInstanceState) {
  super.onCreate(null);

  // set up the edge-to-edge display
  final boolean darkContentBars = true;
  final Window window = getWindow();
  final View view = window.getDecorView();

  final WindowInsetsControllerCompat insetsController =
    new WindowInsetsControllerCompat(window, view);

  WindowCompat.setDecorFitsSystemWindows(window, false);

  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1) {
    window.clearFlags(
      WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS |
        WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION
    );

    window.setStatusBarColor(Color.TRANSPARENT);
    window.setNavigationBarColor(Color.TRANSPARENT);

    insetsController.setAppearanceLightStatusBars(darkContentBars);
    insetsController.setAppearanceLightNavigationBars(darkContentBars);

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
      window.setStatusBarContrastEnforced(false);
      window.setNavigationBarContrastEnforced(false);
    }
  } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
    window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
    window.addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION);

    window.setStatusBarColor(Color.TRANSPARENT);

    insetsController.setAppearanceLightStatusBars(darkContentBars);
  } else {
    window.addFlags(
      WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS |
        WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION
    );
  }
}
```

By doing so, this creates a shift that must be handled for each `react-native-keyboard-controller` component / hook, like, for example (chat example):

```ts
const { height: telegram } = useTelegramTransitions();
const { height: platform } = useReanimatedKeyboardAnimation();
const { bottom: bottomInset } = useSafeAreaInsets();

const height = useDerivedValue(
  () => (isTGTransition ? telegram.value : platform.value) - bottomInset,
  [isTGTransition, bottomInset]
);
```

In this video, it's not handled on the first screen, but it is on the second:

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/1902323/794b342e-99b1-4fd3-907b-8228dcf6ba62

To handle it on the first screen, we need an `Animated.subtract(height, bottomInset)`. But shouldn't it be handled as `navigationBarTranslucent` is `true`?

WIP code: https://github.com/kirillzyusko/react-native-keyboard-controller/commit/3080d972705aae8c809f73360ee51e0595e6ec7c

**Comment by kirillzyusko** [comment]
Hi @zoontek 

I think you also need to set `<item name="android:windowTranslucentNavigation">true</item>` and only then it will stretch to edge-to-edge

And I think you are right, current implementation of RNKC has a bug - when I calculate keyboard height I always subtract `navigationBar` height: https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt#L356

And you are right, it seems like we don't need to subtract if `navigationBarTranslucent=true`

Let me know what do you think :)

**Comment by zoontek** [comment]
`<item name="android:windowTranslucentNavigation">true</item>` set the navigation bar to semi-transparent (in such cases, there's no need for an additional `<NavigationBar />` component, indeed), this code is used to make it fully transparent (like what's possible with `<StatusBar />`)

Just tried it, removing `- navigationBar` does not seems to have an impact here 😕

**Comment by kirillzyusko** [comment]
> Just tried it, removing - navigationBar does not seems to have an impact here 😕

Hm, interesting, I thought it should have an impact 🤔 I'll try to test your code tomorrow 👀

**Comment by kirillzyusko** [comment]
Hello @zoontek 

You'll need to change:

```kt
val diff = Insets.subtract(typesInset, Insets.NONE).let {
  Insets.max(it, Insets.NONE)
}
```

Then the result will be (don't pay an attention to blue circle - it's replica of keyboard animation and was part of very early experiments):

<img width="283" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/c5a125b2-86d2-466f-82ee-fcd78d495bbe">

So my assumption is that we can pass `persistentInsetTypes` as optional param (and if it's optional then use `Insets.NONE` in `onProgress` callback).

Also as I said earlier similar changes should be reflected in `getCurrentKeyboardHeight` - if you switch keyboard input type (emoji, gifs) then circle will be cut off again:

<img width="276" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/46344365-3911-4de7-ab3e-b3838f637513">

Also you can reach out to me via [discord](https://discordapp.com/users/973642097888489512) (nickname is `kiryl.ziusko`) - I'm responding there much faster 👀

**Comment by zoontek** [comment]
@kirillzyusko That's it! We can even simplify this to:

```kotlin
// We coerce the insets to be >= 0, to make sure we don't use negative insets.
val diff = Insets.max(typesInset, Insets.NONE)
```

I never actually realized that you **shouldn't** subtract system bars insets in edge-to-edge mode, given the fact that I blindly followed [this page of their documentation](https://developer.android.com/develop/ui/views/layout/sw-keyboard) and their app examples ([here](https://github.com/android/user-interface-samples/blob/39741e7f101e397811815ab9c7d456ad00d099a7/WindowInsetsAnimation/app/src/main/java/com/google/android/samples/insetsanimation/TranslateDeferringInsetsAnimationCallback.kt#L67) and [here](https://github.com/android/user-interface-samples/blob/39741e7f101e397811815ab9c7d456ad00d099a7/WindowInsetsAnimation/app/src/main/java/com/google/android/samples/insetsanimation/ConversationFragment.kt#L62)).

But this makes no sense at all when you draw under the system bars 🤔
Dropping systemBars insets substraction makes the JS code [much more simpler to think about](https://github.com/zoontek/react-native-keyboard-controller/commit/560968e44906d9664848182d1040829671df5a27).

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/1902323/03396e0e-efcf-4f9e-86d5-681cc9a10724

I'm still in favor of having a proper edge-to-edge layout with fully transparent bars by default (and not really having a choice), as this kind of issues are hard to compose with, given the fact that a user might have, and it's kinda hard for you to handle 4 cases (+ non transparent system bars does not exist on iOS, so this would actually reduce the fragmentation between the 2 platforms 😄):

|        | Transparent status bar | Transparent navigation bar |
| ------ | ---------------------- | -------------------------- |
| Case 1 | ❌                     | ❌                         |
| Case 2 | ✅                     | ❌                         |
| Case 3 | ❌                     | ✅                         |
| Case 4 | ✅                     | ✅                         |

Anyway, I will reach you on Discord next time, thanks for your help 🙂
