### ISSUE TITLE
Trying to read  "y" of undefined due to minimum required version of reanimated 

### ISSUE THREAD

**Issue by Cancercookie** [kirillzyusko/react-native-keyboard-controller#283]
**Describe the bug**

I added this library to my project and set it up when I immediately got an error `"trying to read 'y' of undefined"` on line 75 in `components/KeyboardAvoidingView/index.tsx`

After some try and error I discovered that the project's `react-native-reanimated` version was too low (2.13.0). 
After upgrading to 3.0.2 it stopped throwing the error and all worked flawlessly.

**Code snippet**

I don't know for sure if it was some weird combo of libraries so I will list the ones I upgraded:

```
react-native-gesture-handler: 2.14.0 (was 2.9.0)

react-native-reanimated: 3.0.2 (was 2.13.0)

react-native-safe-area-context: 4.7.4 (was 4.5.0)
```

**Expected behavior**

Add to the compatibility page that at least version 3 of react-native-reanimated is required or prevent the app from crashing due to this bug

**Smartphone (please complete the following information):**
 - Desktop OS: MacOS 14
 - Device: any
 - OS: any
 - RN version: 0.70.8 
 - React version 18.1.0
 - RN architecture: Fabric
 - JS engine: Hermes
 - Library version: 1.9.4

**Additional context**

At the moment I am not able to revert my environment to the previous config due to time limitations within my org.

**Comment by kirillzyusko** [comment]
Hello @Cancercookie 

Thank you for submitting the issue! Actually, you are right - I haven't tested REA 2.x since I added RN 0.72 support. But theoretically the library should be compatible with REA 2.x

The error you are referring to most likely happens here: 

```tsx
return Math.max(frame.value.y + frame.value.height - keyboardY, 0);
```

And frame is derived in next way:

```tsx
const defaultLayout: LayoutRectangle = {
  x: 0,
  y: 0,
  width: 0,
  height: 0,
};

const initialFrame = useSharedValue<LayoutRectangle | null>(null);
const frame = useDerivedValue(() => initialFrame.value || defaultLayout);
```

So theoretically `frame.value` should never be `undefined` 🤷‍♂️ 

I think the error may come because of the fact that `defaultLayout` is not a shared value? Anyway, if you are able to debug it a little bit I would be very thankful to you 🙏

**Comment by kirillzyusko** [comment]
@Cancercookie I've created small repro using next dependencies:

<img width="540" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/ec7f306d-0b1d-487c-b538-1f0c548ae0c6">

And it works fine on iOS for me:

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/e1c555aa-8b9f-4b7c-8d73-207c17156ce9

**Comment by kirillzyusko** [comment]
I'm going to close the issue due to inactivity.

I proved that it should work with REA 2.3+ - maybe your project had a specific setup 🤷‍♂️ I don't know 🙂 

But I'm glad that bumping REA version helped you. If more people will report this problem, then I'll add a note in documentation 👍

**Comment by taha200** [comment]
Hi @kirillzyusko,

I am working with your library and encountering the issue in android and iOS both.

`    "react-native-keyboard-controller": "1.9.4",
    "react-native": "0.71.14",
    "react-native-reanimated": "2.14.1",
`
