### ISSUE TITLE
Cant use KeyboardGestureArea with inverted Flatlist.

### ISSUE THREAD

**Issue by batuhansahan** [kirillzyusko/react-native-keyboard-controller#295]
While attempting to replicate precise keyboard animations in WhatsApp iOS app, I encountered an issue where, upon scrolling to dismiss the keyboard, the gesture area also scrolls the flatlist to the top unexpectedly.

What i expect:
In WhatsApp, the scrolling automatically halts upon tapping the keyboard area, with the sole action being the closure of the keyboard itself.

I tried examples in the example folder
[https://github.com/kirillzyusko/react-native-keyboard-controller/blob/64dc299f08b6440bbc8809180836b6a6979e0aba/example/src/screens/Examples/ReanimatedChatFlatlist/index.tsx](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/64dc299f08b6440bbc8809180836b6a6979e0aba/example/src/screens/Examples/ReanimatedChatFlatlist/index.tsx)

changed like this.

```
    <View style={styles.container}>
      <KeyboardGestureArea interpolator="ios">
        <FlatList
          inverted
          keyboardShouldPersistTaps="always"
          keyboardDismissMode="interactive"
          initialNumToRender={15}
          contentContainerStyle={styles.contentContainer}
          data={reversedMessages}
          renderItem={RenderItem}
        />
      </KeyboardGestureArea>
      <TextInput style={styles.textInput} />
      <Animated.View style={fakeView} />
    </View>
```

**Comment by kirillzyusko** [comment]
Hello @batuhansahan 

Can you provide a minimal reproduction example, provide info about your device/environment, and attach a video to show the actual problem?

**Comment by kirillzyusko** [comment]
I'm closing the issue due to inactivity. Feel free to open a new issue and attach a code to reproduce the behavior, attach info about your environment, screenshots/videos and everything else that specified in issue template.
