### ISSUE TITLE
 failed to create a worklet - when importing KeyboardProvider

### ISSUE THREAD

**Issue by ShaulBenDavid** [kirillzyusko/react-native-keyboard-controller#301]
**Describe the bug**
I installed the library and a
![Screenshot 2023-12-18 at 10 15 00](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/79593694/85132934-0725-40e7-a007-8645f6d2ee87)
dded a swift file.
When I run the app every things work than I try to import the KEyboardProvider and I get this error

**Code snippet**
`               <KeyboardProvider statusBarTranslucent>
                    <SafeAreaProvider>
                      <Toaster />
                      <Navigation />
                    </SafeAreaProvider>
                  </KeyboardProvider>`

**To Reproduce**
npm install react-native-keyboard-controller
pod install
swift file in xcode
run ios
import KeyboardProvider

**Expected behavior**
App run without 

**Screenshots**
![Screenshot 2023-12-18 at 10 15 00](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/79593694/b17ef45e-ac9c-43e4-8332-5b64bcb7a0d8)
error

**Smartphone (please complete the following information):**
 - Desktop OS: [e.g. Windows 10, MacOS 10.15.5]
 - Device: [e.g. iPhone8]
 - OS: [e.g. iOS 10.0]
 - RN version: [e.g. 0.68.2]
 - RN architecture: [e.g. old/new or paper/fabric]
 - JS engine: [e.g. JSC, Hermes, v8]
 - Library version: [e.g. 1.2.0]

**Comment by kirillzyusko** [comment]
Hello @ShaulBenDavid 

Do you have `react-native-reanimated` installed?

**Comment by ShaulBenDavid** [comment]
@kirillzyusko 
no and if I install `react-native-reanimated ` the pod install fail

**Comment by kirillzyusko** [comment]
@ShaulBenDavid what is the error during pod installation?

**Comment by ShaulBenDavid** [comment]
@kirillzyusko 
![Screen Shot 2023-12-19 at 08 24 15 AM](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/79593694/72b1bf11-0319-4541-96da-f9f8a6d9bca8)

**Comment by kirillzyusko** [comment]
@ShaulBenDavid which RN version are you using?

**Comment by ShaulBenDavid** [comment]
@kirillzyusko "react-native": "0.72.3"

**Comment by kirillzyusko** [comment]
@ShaulBenDavid well, last assumption - can you updated `cocoapods` to latest version and try again?

And you are right, right now this package heavily relies on `reanimated` package. I had a plan to make the dependency optional (of course hooks that depends on Reanimated will not work anymore and will produce a warning), but haven't implemented it yet.

**Comment by ShaulBenDavid** [comment]
@kirillzyusko 
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.0/lib/cocoapods.rb

**Comment by kirillzyusko** [comment]
@ShaulBenDavid you are using `1.12.0` while the latest one is `1.14.3`. Just think that it could be the issue (but i don't know - just trying to compare with my local setup).

**Comment by pouyaemami** [comment]
Hey all, I seem to be running into this same issue but I have no problems installing the pods. Additionally, I am seeing this on both iOS and Android. I'm running RN 0.73.5 and version 1.11.6 of this library.

I tried to follow [these steps](https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting/#failed-to-create-a-worklet) as I am getting an error regarding worklets but that doesn't seem to change anything.

I also tried to eliminate all other providers in case that was causing this issue but that too did not help.

Any help would be greatly appreciated :)

**Comment by kirillzyusko** [comment]
Hello @pouyaemami 

Did you restart metro server and cleaned a cache? I am referring to this [step](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started#step-3-clear-metro-bundler-cache-recommended)

**Comment by pouyaemami** [comment]
Yes I also tried to do that. I am currently looking into `npx react-native-clean-project` to see if that will fix it.

**Comment by kirillzyusko** [comment]
@pouyaemami what happens if you remove `KeyboardProvider` and simply create an animation component in App.tsx as described here https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/your-first-animation?

Will it throw exception or not?

**Comment by pouyaemami** [comment]
@kirillzyusko thanks for suggesting that check. I tried that and realised that `react-native-reanimated` needs to be added as a direct dependency for my project. Once I did that, running `pod install` added the package for iOS and now I am no longer getting that error.

I know that your package brings it in as a dependency but for some reason, running pod install doesn't install doesn't install `react-native-reanimated` when I only have your package as a direct dependency for my project. Not sure if I missed something in the setup guide you have.

Thanks again so much!

**Comment by kirillzyusko** [comment]
> I know that your package brings it in as a dependency but for some reason, running pod install doesn't install doesn't install react-native-reanimated when I only have your package as a direct dependency for my project. Not sure if I missed something in the setup guide you have.

No, I believe you did everything correctly - for some reasons I missed this info in my installation guide 🙈 I'll fix it shortly 👍 

In `react-native` world declaring something as `peerDependency` will not add it in Pod and will not link it natively, so yeah, `react-native-reanimated` has to be declared in your app dependencies.

Thank you for your comments and I'm glad you finally managed to make everything working! 💪

**Comment by kirillzyusko** [comment]
Actually I thought a little bit more and decided, that for now I'll close the issue - now it's mandatory to install reanimated.

Maybe in future I'll revisit the approach and make the reanimated dependency optional, but right now all components (`KeyboardAvoidingView`, `KeyboardAwareScrollView` and `KeyboardStcikyView`) are using and heavily rely on reanimated, so I'll keep it mandatory and close the issue.

Thanks @pouyaemami and @ShaulBenDavid for your reports and help to resolve the problem 💪
