### ISSUE TITLE
KeyboardAccesoryView Input navigation arrows  

### ISSUE THREAD

**Issue by VladyslavMartynov10** [kirillzyusko/react-native-keyboard-controller#303]
In some recent applications, I've noticed KeyboardAccessoryView with navigation prev/next arrows & action done button. I understand that this was designed for enhanced user accessibility and quicker navigation between input fields, eliminating the need to scroll down to focus on the necessary input.

I was searching for references that could potentially be used for implementation and found only this library:
https://github.com/douglasjunior/react-native-keyboard-manager. The main issue with this implementation is that it's available only on iOS, and in some cases, it cannot be fully controlled by the developer.

Moreover, after a couple of hours, I created a KeyboardAccessoryView based on `KeyboardStickyView` right out of the box, resulting in the following component:

```tsx
import React, { useMemo } from 'react';
import { Keyboard, StyleSheet, TouchableOpacity, View, Text } from 'react-native';
import {
  KeyboardStickyView,
  useReanimatedKeyboardAnimation,
} from 'react-native-keyboard-controller';
import Animated, {
  Extrapolate,
  interpolate,
  useAnimatedStyle,
} from 'react-native-reanimated';
import { Icon } from 'react-native-vector-icons';


interface KeyboardAccessoryViewProps {
  onNextPress?: () => void;
  onPrevPress?: () => void;
  onDoneButtonPress?: () => void;
}

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row'
  }
});

export const KeyboardAccessoryView: React.FC<KeyboardAccessoryViewProps> = ({
  onNextPress,
  onPrevPress,
  onDoneButtonPress,
}) => {
  const offset = useMemo(() => ({ closed: 0, opened: 0 }), []);

  const { progress } = useReanimatedKeyboardAnimation();

  const onDonePress = () => {
    Keyboard.dismiss();
  };

  const onNext = () => {
    onNextPress?.();
  };

  const onPrev = () => {
    onPrevPress?.();
  };

  const animatedStyle = useAnimatedStyle(() => {
    return {
      opacity: interpolate(progress.value, [0, 1], [0, 1], Extrapolate.CLAMP),
      transform: [
        {
          translateY: interpolate(
            progress.value,
            [0, 1],
            [30, 0],
            Extrapolate.CLAMP,
          ),
        },
      ],
    };
  });

  return (
    <Animated.View style={[animatedStyle]}>
      <KeyboardStickyView offset={offset} style={styles.container}>

        <View style={styles.container}>
          <TouchableOpacity
              onPress={onNext}
            >
              <Icon name="chevron-thin-up" />
          </TouchableOpacity>
          
        

        <TouchableOpacity
              onPress={onPrev}
            >
              <Icon name="chevron-thin-down" />
          </TouchableOpacity>

        </View>  

        <TouchableOpacity onPress={onDonePress}>
            <Text>
              Done
            </Text>
          </TouchableOpacity>
       

      </KeyboardStickyView>
    </Animated.View>
  );
};
```

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/115457344/683888a9-0207-4297-afaa-6eed54d9b68d

It works perfectly with full keyboard animation synchronization, but it requires additional logic in the React Native environment to handle all the states:

- prev/disabled buttons opacity
- show prev/next buttons
- support dynamic input quantity
- dynamic placeholder in the centre of the `KeyboardAccesoryView`
- customization  for `Done, prev/next buttons` on react-native-side  

It would be great to have such a feature component available right out of the box, in order to minimize JavaScript implementation. Perhaps it will be useful for someone in the future.

**Comment by VladyslavMartynov10** [comment]
@kirillzyusko I'm sorry, need to be moved to feature request

**Comment by kirillzyusko** [comment]
Good proposal @VladyslavMartynov10 

I'll see how it's implemented in `IQKeyboardManager` (library that used in `react-native-keyboard-manager`) and will try to follow a similar way in Android (but of course it'll require some time for a research).

May I ask you how you implemented `onNextPress`/`onPrevPress`/`onDoneButtonPress`? Did you create kind of registry for your text inputs (array of `TextInput` refs)?

**Comment by VladyslavMartynov10** [comment]
@kirillzyusko Just a simple hook for handling navigation arrows:

```
import React, { useMemo, useState } from 'react';
import { TextInput } from 'react-native';

export const useKeyboard = (length: number) => {
  const inputRefs = useMemo(
    () => Array.from({ length }, () => React.createRef<TextInput>()),
    [length],
  );

  const [activeInputIndex, setActiveInputIndex] = useState(0);
  const [focusLimits, setFocusLimits] = useState({ nextDisabled: false, previousDisabled: false });

  const updateFocusLimits = (index: number) => {
    setFocusLimits({
      nextDisabled: index === length - 1,
      previousDisabled: index === 0,
    });
  };

  const handleFocus = (index: number) => () => {
    updateFocusLimits(index);
    setActiveInputIndex(index);
  };

  const handleFocusNext = () => {
    const newIndex = activeInputIndex + 1;
    if (newIndex < length) {
      inputRefs[newIndex]?.current?.focus();
    }
  };

  const handleFocusPrevious = () => {
    const newIndex = activeInputIndex - 1;
    if (newIndex >= 0) {
      inputRefs[newIndex]?.current?.focus();
    }
  };

  return {
    inputRefs,
    activeInputIndex,
    focusLimits,
    handleFocus,
    handleFocusNext,
    handleFocusPrevious,
  };
};
```
Modified example from repository:

```
import React from 'react';
import { useResizeMode } from 'react-native-keyboard-controller';

import KeyboardAwareScrollView from '../../../components/AwareScrollView';
import { styles } from './styles';
import { useKeyboard } from './hooks';
import { View } from 'react-native';
import { KeyboardAccessoryView } from './KeyboardAccessoryView';
import { StyleSheet, TextInput as TextInputRN } from 'react-native';


const stylesT = StyleSheet.create({
  container: {
    width: '100%',
    minHeight: 50,
    maxHeight: 200,
    marginBottom: 50,
    borderColor: 'black',
    borderWidth: 2,
    marginRight: 160,
    borderRadius: 10,
    color: 'black',
    paddingHorizontal: 12,
  },
});


export default function AwareScrollView() {
  useResizeMode();

  const {
    handleFocus,
    handleFocusNext,
    handleFocusPrevious,
    inputRefs,
  } = useKeyboard(10);

  return (
    <View style={{flex: 1}}>

    <KeyboardAwareScrollView  bottomOffset={70} keyboardDismissMode='none' keyboardShouldPersistTaps='always' style={styles.container} contentContainerStyle={styles.content}>

        <TextInputRN
          ref={inputRefs[0]}
          onFocus={() => handleFocus(0)}
          style={stylesT.container}
        />

        <TextInputRN
          ref={inputRefs[1]}
          onFocus={handleFocus(1)}
          style={stylesT.container}
        />

        <TextInputRN
          ref={inputRefs[2]}
          onFocus={handleFocus(2)}
          style={stylesT.container}
        />

        <TextInputRN
          ref={inputRefs[3]}
          onFocus={handleFocus(3)}
          style={stylesT.container}
        />

        <TextInputRN
          ref={inputRefs[4]}
          onFocus={handleFocus(4)}
          style={stylesT.container}
        />

    </KeyboardAwareScrollView>

    <KeyboardAccessoryView
      onNextPress={handleFocusNext}
      onPrevPress={handleFocusPrevious}
    /> 
        
    </View>
  );
}
```

**Comment by kirillzyusko** [comment]
Okay, I studied an implementation of `IQKeyboardManager`. First of all - it's not a native component/implementation. It's custom code, so it should be replicable to Android (the basic algorithm is searching for a parent view of focused view and then getting all sibling TextInputs).

The implementation of `IQKeyboardManager` is quite powerful, because:
- you can specify order using different ways: subview/tag/position;
- you can create custom order (and skip some fields if needed, but in this case it's similar to what can be achieved using refs and custom logic);
- you can go to non TextInputs:

<img width="394" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/5332d9a9-d490-4754-b414-23753e72bd2c">

<hr />

>  it cannot be fully controlled by the developer

@VladyslavMartynov10 May I ask you what exactly you would like to control that `RNKM` is not offering?

I was thinking about `KeyboardController.moveFocuseToInput("prev" | "next")` API. The order could be specified as a numeric value (via `nativeId` property?) and siblings inputs could be discovered similarly to `IQKeyboardManager` algorithm (or you could also specify a container as a lookup point, also via `nativeId` prop?).

Also you need to know which input is currently focused, so we'll need to give an access to two values:
- number of input that currently holds a focus (i, e, 0/2/10);
- amount of all inputs (i. e. 10).

Is there anything else that I'm missing? Would it be enough to have such API:

```tsx
const { focused, all } = await KeyboardController.moveFocuseTo("prev" | "next"); // { focused: 2, all: 10 }
```

or do you think something else is still needed?

**Comment by VladyslavMartynov10** [comment]
For now `nativeID + IQKeyboardManager` algorithm looks promising. It's better to start with some basic features at least prev/next & done buttons callbacks and then in the next release add all necessary custom functions.

Thanks for investigation!

**Comment by kirillzyusko** [comment]
Just a quick update - I'm working hard on this feature 💪 

This is a demo of what I have at the moment:

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/18224a2b-3140-4514-ab58-f575aab89700

Basically it works and implementation of view traversal is fully on native side (i. e. you don't need to do a magic with refs, etc.). There are still a lot of work to do, especially:
- manage disabling/enabling of next/prev buttons;
- improve Toolbar component (UI/accessibility/animations/customization/dark theme support)
- more complex form logic; 
- many other bugfixes 🙂 

The branch where I'm doing all my experiments is https://github.com/kirillzyusko/react-native-keyboard-controller/tree/feat/move-focus-to

**Comment by VladyslavMartynov10** [comment]
It looks fantastic. Interesting traversal view approach, need to check it later 🙂

**Comment by kirillzyusko** [comment]
> sometimes scrolling is not as smooth as native

Scrolling still depends on `KeyboardAwareScrollView` implementation 🙃 On a native side I'm doing a view traversal just to detect sibling `TextInputs` and find next input in hierarchy 👀 

Yes, sure, feel free to grab that code and let me know your concerns/feature requests 👀 That would be very helpful to gather a feedback on early stage of implementation 🙏

**Comment by VladyslavMartynov10** [comment]
I've made several tests on both Platforms seems to be work okay. 

Additionally, the first idea that quickly came to my mind is the use of a LinkedList instead of recursion. In this case we can easily detect prev/next states and simplify deep-search in view hierarchy. Please let me know if you have any concerns about this. The only issue that might be time-consuming is the insertion process.

As for the to-do list, I will also add support for dynamic placeholders in the middle of the ToolBar.
