### ISSUE TITLE
iOS memory leak（1.10.0）

### ISSUE THREAD

**Issue by rabbitmouse** [kirillzyusko/react-native-keyboard-controller#317]
I found that after using the <KeyboardProvider>, the fastImage used on the page will not be released, and the KeyboardControllerView would not execute deinit.

**Code snippet**
```
const Page = () => {
  const images = [
    require('../assets/img1.png'),
    require('../assets/img2.png'),
    require('../assets/img3.png'),
    require('../assets/img4.png'),
    require('../assets/img5.png'),
    require('../assets/img6.png'),
    require('../assets/img7.png'),
    require('../assets/img8.png'),
  ];
  return (
    <KeyboardProvider
      statusBarTranslucent={true}
      navigationBarTranslucent={true}>
      <View className="flex-1 bg-red-200 items-center justify-center">
        {images.map(item => {
          return <FastImage source={item} className="w-160 h-100 mb-10" />;
        })}
      </View>
    </KeyboardProvider>
  );
};
```

**Repo for reproducing**
"react-native-keyboard-controller": "1.10.0",
"react-native-fast-image": "8.6.3",

- Desktop OS: [e.g. Windows 10, MacOS 10.15.5]
- Device: iPhone12
- OS: iOS16、iOS17
- RN version: 0.72.1
- JS engine: Hermes

**Comment by kirillzyusko** [comment]
@rabbitmouse may I kindly ask you to provide full reproduction repo and the way how you find memory leaks?

Deinit (from my observation) will not be called if the screen was closed (instead `override func willMove(toSuperview newSuperview: UIView?) {` will be called).

Are you assuring that if you remove `KeyboardProvider` then memory leaks are gone?

**Comment by VladyslavMartynov10** [comment]
@rabbitmouse I think the problem lies in `react-native-fast-image` implementation starting from iOS 17.0+ versions. I've caught lots of app freezes especially in dev mode even with simple components.

 Does this problem exist with in release mode?

**Comment by rabbitmouse** [comment]
I used instruments to check the memory and found that after using ```KeyboardProvider``` to wrap ```FFFFastImageView```, the reference count of fastimageview will not eventually reduce to 0.

**Comment by rabbitmouse** [comment]
> @rabbitmouse I think the problem lies in `react-native-fast-image` implementation starting from iOS 17.0+ versions. I've caught lots of app freezes especially in dev mode even with simple components.
> 
> Does this problem exist in release mode?

i checked with QA, the release mode and iOS 16 still has this problem 

I debugged and found that when the page exits, ```willMove``` will be executed but ```deinit``` will not be executed in KeyboardControllerViewManager.swift.
