### ISSUE TITLE
Expose style prop of chidren of KeyboardAwareScrollView

### ISSUE THREAD

**Issue by sem4phor** [kirillzyusko/react-native-keyboard-controller#325]
**Is your feature request related to a problem? Please describe.**
When using the KeyboardAwareScrollView component with react-native-web there is no way in styling it's internal child (`<Reanimated.View style={view}>{children}</Reanimated.View>`) which I need to do because it needs to span the whole screen for me and therefore i have to add `flex: 1` to it somehow.

**Describe the solution you'd like**
Expose the style prop of that child.

**Describe alternatives you've considered**
Importing a css file on some other way and target that div.

**Comment by kirillzyusko** [comment]
@sem4phor will this PR https://github.com/kirillzyusko/react-native-keyboard-controller/pull/321 fix your problem?

I think then you can specify `contentContainerStyle={{flex: 1}}` and it should work, right?

**Comment by sem4phor** [comment]
Yes thank you 🙏
