### ISSUE TITLE
[ios] build error 'react_native_keyboard_controller-Swift.h' file not found

### ISSUE THREAD

**Issue by dioi2000** [kirillzyusko/react-native-keyboard-controller#354]
![스크린샷 2024-02-07 오전 10 18 17](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/33106641/79ba98b4-942d-4ceb-a677-ea6ab4cb923c)
 build error 'react_native_keyboard_controller-Swift.h' file not found when ios build

- Desktop OS: macOS 14.1.1
- RN version: 0.72.8
- RN architecture: new fabric
- Library version: 1.10.5 / 1.9.5 tested

**Comment by kirillzyusko** [comment]
@dioi2000 can you create a small reproduction example? Are you using dynamic frameworks?

**Comment by kirillzyusko** [comment]
@dioi2000 or which changes do I need to make in my `FabricExample` in order to reproduce the error?

**Comment by dioi2000** [comment]
@kirillzyusko it seems like happens when disable  :flipper_configuration => flipper_config,
i will share example project soon

**Comment by kirillzyusko** [comment]
Thank you @dioi2000 

I've tried to enable static frameworks and disable flipper, but I'm getting compilation issues in `react-native-screens` then 🤷‍♂️ 

So yeah, it would very helpful if you could share a reproduction example 🙏

**Comment by dioi2000** [comment]
@kirillzyusko 
there is some changes on podfile and commented with [change] annotation

[testApp.zip](https://github.com/kirillzyusko/react-native-keyboard-controller/files/14192673/testApp.zip)

**Comment by kirillzyusko** [comment]
@dioi2000 can you check if https://github.com/kirillzyusko/react-native-keyboard-controller/pull/355 fixes the problem?

**Comment by dioi2000** [comment]
@kirillzyusko cool problem fixed

**Comment by kirillzyusko** [comment]
Published a fix under `1.10.7` version
