### ISSUE TITLE
is there any hooks that i can use to determine if keyboard is visible or not?

### ISSUE THREAD

**Issue by ddikodroid** [kirillzyusko/react-native-keyboard-controller#386]
First, thank you for making this package. It helps me to solve the keyboard issue on my project.

I have this code below
```tsx
import {KeyboardAwareScrollView} from 'react-native-keyboard-controller';

  <KeyboardAwareScrollView
      contentContainerStyle={[
        styles.contentContainer,
        {
          paddingBottom: isIos ? insets.bottom * 4 : spacing.xxl * 2,
        },
      ]}>
...
</KeyboardAwareScrollView>

```
I set the paddingBottom because my bottom component is hidden behind the bottom tab. But, when the keyboard is open, the padding is really visible.
<img width="432" alt="Screenshot 2024-03-15 at 19 54 12" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/4207774/52196c2f-8b99-4464-9022-6f2d04107219">

I want to set the paddingBottom to 0 when the keyboard is open. How to do that?

Thanks in advance!

**Comment by kirillzyusko** [comment]
Hey @ddikodroid 

Can you use something like this?

```tsx
const useKeyboardVisibility = () => {
  const [setVisible, isVisible] = useState(false);

  useEffect(() => {
    const willOpenSubscription =  KeyboardEvents.addListener("keyboardWillShow", (e) => {
      setVisible(true);
    });
    const willHideSubscription =  KeyboardEvents.addListener("keyboardWillHide", (e) => {
      setVisible(false);
    });
    
    return () => {
      willOpenSubscription.remove();
      willHideSubscription.remove();
    }
  }, []);

  return isVisible;
}
```

**Comment by ddikodroid** [comment]
> Hey @ddikodroid
> 
> Can you use something like this?
> 
> ```tsx
> const useKeyboardVisibility = () => {
>   const [setVisible, isVisible] = useState(false);
> 
>   useEffect(() => {
>     const willOpenSubscription =  KeyboardEvents.addListener("keyboardWillShow", (e) => {
>       setVisible(true);
>     });
>     const willHideSubscription =  KeyboardEvents.addListener("keyboardWillHide", (e) => {
>       setVisible(false);
>     });
>     
>     return () => {
>       willOpenSubscription.remove();
>       willHideSubscription.remove();
>     }
>   }, []);
> 
>   return isVisible;
> }
> ```

thank you so much, it's working!

**Comment by kirillzyusko** [comment]
> just need to reorder the setVisible and isVisible

Oh, yeah, my bad 🙈 😅
