### ISSUE TITLE
can't complie in android 

### ISSUE THREAD

**Issue by jamninetyfive** [kirillzyusko/react-native-keyboard-controller#4]
Hi. first of all . Thanks for your work . that's pretty nice work.

in my exists project  can't complie in android studio

android studio 4.1.3
gradle 5.6.4
kotlin 1.3.24

i got error like kotlin version too high about this.

i wanna know how to work fine and don't change the kotlin version and gradle version.

**Comment by jamninetyfive** [comment]
The binary version of its metadata is 1.6.0, expected version is 1.4.2.

**Comment by kirillzyusko** [comment]
Hi @jamninetyfive 

Could you attach original error, please?

I've used latest Kotlin version in example project, so yeah, it can be an issue😅

**Comment by jamninetyfive** [comment]
[log.txt](https://github.com/kirillzyusko/react-native-keyboard-controller/files/8585026/log.txt)
log here .

**Comment by kirillzyusko** [comment]
@jamninetyfive could you check whether https://github.com/kirillzyusko/react-native-keyboard-controller/pull/5 fixes the problem?

**Comment by jamninetyfive** [comment]
it's work, thanks!
