### ISSUE TITLE
KeyboardAwareScrollView not work in TextInput nested in FlatList component

### ISSUE THREAD

**Issue by elenydev** [kirillzyusko/react-native-keyboard-controller#401]
**Describe the bug**
Hey, i'm facing issue with `KeyboardAwareScrollView  - When im trying to use it above the level of `FlatList` it does not work.

![image](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/63653256/560ec4bb-de7f-4677-bb17-51ee4c127e8d)

Is there any specific way that i should handle it?
Of course, in the renderItem of flat list i does not have only the TextInput, but whole component with textInput in it

**Comment by kirillzyusko** [comment]
@elenydev `FlatList` under hood renders its own `ScrollView`. So your layout will contain two `ScrollView`s:

```tsx
<ScrollView> // <- KeyboardAwareScrollView
  <ScrollView> // <- FlatList
```

And `ScrollView` rendered by `FlatList` is simple `ScrollView` which doesn't have avoiding behavior. In your case you can try to render `KeyboardAwareScrollView` [inside](https://reactnative.dev/docs/virtualizedlist#renderscrollcomponent) `FlatList`:

```tsx
<FlatList
  renderScrollComponent={KeyboardAwareScrollView}
/>
```

Can you try this and see if it fixes your problem?

**Comment by elenydev** [comment]
@kirillzyusko thanks for fast reply!

Actually, passing the `KeyboardAwareScrollView` like You've showed result in 

![image](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/63653256/8de2de9a-1ad1-4b4d-a0f6-00086aba7c50)

![image](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/63653256/a599365c-8b98-4e5a-b2b6-84ec676a9a66)

This way it renders the list, but unfortunately it's not solving the issue :(

**Comment by kirillzyusko** [comment]
@elenydev can you post the code sample here, so that I can run it in my example app and see what exactly is not working? 👀

**Comment by elenydev** [comment]
https://snack.expo.dev/@eleny/keyboardavoidingview - You can take straight from here - also You can try to play with renderScrollComponent

@kirillzyusko

**Comment by kirillzyusko** [comment]
@elenydev here is a slightly modified version of your code:

```tsx
import React from "react";
import { FlatList, TextInput, View } from "react-native";
import { KeyboardAwareScrollView } from "react-native-keyboard-controller";

const foo = [...Array(100).keys()];

const KeyboardAvoidingComponent = () => {
  return (
    <View style={{ flex: 1, background: "black" }}>
      <FlatList
        data={foo}
        renderItem={() => (
          <View style={{ width: "100%", height: 50 }}>
            <TextInput
              placeholder="Some input"
              style={{
                color: "blue",
                margin: 20,
                borderColor: "red",
                height: 30,
                borderWidth: 1,
              }}
            />
          </View>
        )}
        renderScrollComponent={(props) => (
          <KeyboardAwareScrollView bottomOffset={10} {...props} />
        )}
      />
    </View>
  );
};

export default KeyboardAvoidingComponent;
```

`KeyboardProvider` and other app providers are located in `App.tsx` so I didn't put them here, but you can find them in example app.

Works like a charm:

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/4a32301e-020a-4d1a-9458-76fc2a4d951a

Let me know if I can close this issue 👀

**Comment by elenydev** [comment]
@kirillzyusko Yeah, this way it works, but take a closer look on my example :) you're missing `KeyboardAwareScrollView` above flat list - and also the input

**Comment by kirillzyusko** [comment]
@elenydev Ah, you did it with purpose 😅 I thought it was just demonstration of when it works and when not 😅 

I think having two view is incorrect layout, because most likely it will break a virtualization of a FlatList (you should receive a warning) - FlatList will not be able to detect its own size (it'll actually find it, but since it'll be nested in a ScrollView - it will have infinite `height` so it'll try to render all elements).

In your case If you want to have a blue input on top and all other red inputs in FlatList then you can utilize `ListHeaderComponent` property and render there `blue` input, while rendering red inputs in `renderItem`. In this case you'll have a single `ScrollView` and will have a blue input.

Does it make sense what I'm saying?

**Comment by elenydev** [comment]
Works like charm :) Great advice, really appreciate that! I'm learning native version of React, all of those tips are very handful.

Thanks @kirillzyusko , we can close the issue :)
