### ISSUE TITLE
Opening keyboard in audio recording mode

### ISSUE THREAD

**Issue by rlopes** [kirillzyusko/react-native-keyboard-controller#41]
Could it be possible to have the ability to trigger the display of the keyboard in audio recording mode by default?
Ideally both Android and iPhone.

**Comment by kirillzyusko** [comment]
Hi @rlopes 

Sorry for the stupid question, but what do you mean by "audio recording mode"? And what is the platform restrictions regarding keyboard?

Can't you create an invisible `TextInput` and put a focus on this field to trigger keyboard appearance?

**Comment by kirillzyusko** [comment]
@rlopes got it. I think it's not possible (at least I haven't seen such behaviour in native applications) - once you set focus on a `TextInput` it will show a default keyboard. But if you know such apps, where you can tap on TextInput and they open keyboard in dictation mode - let me know, and I will check how they implemented it 👀 

Though, I thunk, if you need to use voice recognition - you can use [react-native-voice](https://github.com/react-native-voice/voice) package - it allows to transform a voice to text using the same API that is used by the system (keyboard).

It will not show keyboard UI, but it's even better 😅  - you can implement your own UI using lottie, etc. and make it really beautiful 🙂 

Let me know, if I helped you and I can close the issue.

**Comment by rlopes** [comment]
I have to admit that I don't know any app from the top of my head that does open in dictation mode when a tap happens.
That being said you make good recommendations here. I will explore those.
Thanks a lot for taking the time to answer my question. Really appreciated.

**Comment by kirillzyusko** [comment]
@rlopes you are welcome :)

I'm going to close this issue, but if you find something - don't hesitate to report a new one issue or reopen this :)
