### ISSUE TITLE
The KeyboardToolbar misbehaves on iPhones when wrapped by SafeAreaView

### ISSUE THREAD

**Issue by Kreshnik** [kirillzyusko/react-native-keyboard-controller#415]
**Describe the bug**
There are two issues: the KeyboardToolbar is visible at the bottom of the view when the keyboard is closed, which I assume is caused by the SafeAreaView. Additionally, when the keyboard opens, the KeyboardToolbar is not completely docked to the keyboard but has an empty space in between.

**Code snippet**
```
  return (
    <SafeAreaView>
      <FlatList
          renderItem={({ item }) => {
            return (
              <Box w="100%">
                <item.component {...item.props} />
              </Box>
          )}}
          renderScrollComponent={(props) => (
            <KeyboardAwareScrollView {...props} style={{flex: 1}} />
          )}
        />
      <KeyboardToolbar doneText="Done" />
    </SafeAreaView>
  );
  ```

**Repo for reproducing**
N/A

**To Reproduce**
N/A

**Expected behavior**
The KeyboardToolbar should not be visible when the keyboard is closed, and there should be no space between the KeyboardToolbar and the Keyboard.

**Screenshots**
<img width="387" alt="Screenshot 2024-04-18 at 23 35 28" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/1788349/c713df36-d261-4f45-9694-28d7520e1133">
<img width="372" alt="Screenshot 2024-04-18 at 23 36 29" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/1788349/dcc9ed6f-6409-49e3-805e-843f6bf23982">

**Smartphone (please complete the following information):**

- Device: iPhone 13 Pro Max
- OS: iOS 17.0
- RN version: ^0.73.7
- RN architecture: new
- JS engine: default
- Library version: ^1.11.6

**Comment by kirillzyusko** [comment]
@Kreshnik hello 👋 

Can you try to render `KeyboardToolbar` outside of `SafeAreaView`? Something like this:

```tsx
return (
  <>
    <SafeAreaView>
      <FlatList
          renderItem={({ item }) => {
            return (
              <Box w="100%">
                <item.component {...item.props} />
              </Box>
          )}}
          renderScrollComponent={(props) => (
            <KeyboardAwareScrollView {...props} style={{flex: 1}} />
          )}
        />
    </SafeAreaView>
    <KeyboardToolbar doneText="Done" />
  </>
);
```

**Comment by kirillzyusko** [comment]
I'm going to close the issue.

`KeyboardToolbar` uses relative positioning, so it always must be in the end of the screen. If you can not put it in the end of the screen, then you can apply additional styles and wrap it within a view:

```tsx
  return (
    <SafeAreaView>
      <FlatList
          renderItem={({ item }) => {
            return (
              <Box w="100%">
                <item.component {...item.props} />
              </Box>
          )}}
          renderScrollComponent={(props) => (
            <KeyboardAwareScrollView {...props} style={{flex: 1}} />
          )}
        />
      <View style={{paddingTop: 30 /* or any other value, like bottom tab bar height */}}>
        <KeyboardToolbar doneText="Done" />
      </View>
    </SafeAreaView>
  );
```

**Comment by kirillzyusko** [comment]
Also in latest versions new `offset` property was added - you can utilize that to achieve conditional positioning 👀

**Comment by g-hamilton** [comment]
I have exactly the same issue. When wrapped in a RN SafeAreaView in iOS, the KeyboardToolbar becomes visible on screen and when the keyboard is opened, there is unwanted space between the keyboard and toolbar, no matter what the bottomOffset of KeyboardAvoidingView is set to. Wrapping the toolbar in a view with padding top does nothing to help the situation. As soon as I remove SafeAreaView from my outer layout it's fine - but then every screen of my app becomes unsafe - which is a major refactor pain.

**Comment by anahids-ff** [comment]
I have the same problem but with `KeyboardAwareScrollView`, I don't know why with `KeyboardAvoidingView` is working. I tried several things, moving the offset from KeyboardToolbar seems to work but not for all the phone sizes, even with `useSafeAreaInsets` hook... I don't know what else to try haha

**Comment by kirillzyusko** [comment]
@anahids-ff could you add a reproduction demo and tell me which iPhones should I test?

> no matter what the bottomOffset of KeyboardAvoidingView is set to. Wrapping the toolbar in a view with padding top does nothing to help the situation. As soon as I remove SafeAreaView from my outer layout it's fine - but then every screen of my app becomes unsafe - which is a major refactor pain.

@g-hamilton I think it's a wrong pattern to embed `KeyboardToolbar` inside the `KeyboardAvoidingView` because `KeyboardToolbar` will avoid keyboard on its own.

You also can use `Portal` to teleport views in desired position if `<KeyboardToolbar offset={{...}}>` doesn't help you. The code can look like this. Such code:

```tsx
const Screen = ({children}) => {
  return (
    <SafeAreaView>{children}</SafeAreaView>
  );
}
```

Will be transformed into:


```tsx
import {Portal, PortalProvider, PortalHost} from "@gorhom/portal"

const Screen = ({children}) => {
  return (
    <PortalProvider>
      <SafeAreaView>{children}</SafeAreaView>
      <PortalHost name="KeyboardToolbar" />
    </PortalProvider>
  );
}

// ... and the somewhere in your code

const Home = () => {
  return (
    <Screen>
      <Portal hostName="KeyboardToolbar">
        <KeyboardToolbar />
      </Portal>
    </Screen>
  );
}
```
