### ISSUE TITLE
keyboard reopens automatically when swipe down on area above keyboard

### ISSUE THREAD

**Issue by esenbi** [kirillzyusko/react-native-keyboard-controller#416]
**Describe the bug**
I use KeyboardStickyView to create chat, where there is text input area above interactive keyboard. 

When i swipe down on the left side of text input keyboard closes and opens again automatiocally. Swipe down on right side doing nothing.

I find out that this happening because of react-navigations swipe back gesture. Only if swipe down inside gesture area.

**Code snippet**
```
<KeyboardStickyView
          style={[
            GlobalStyles.container,
            styles.messagesStyle,
            {paddingBottom: insets.bottom},
          ]}
          offset={offset}>
          <PostsList posts={orderedPosts} />
          <PostCompose ref={bottomSheetRef} id={channel.id} />
        </KeyboardStickyView>
```

**Expected behavior**
Disable that beavior on swipe down

**Screenshots**

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/115775474/b9f54ba2-6ccd-4bfc-8a16-145b85fda5bc

**Smartphone (please complete the following information):**

- Desktop OS: macos
- Device: iPhone 15 simulator
- OS: 17.4
- RN version: 0.72.3
- Library version: 1.11.6

**Additional context**
Temporary fixed by keyboardHandlingEnabled: false stack screen options.

**Comment by kirillzyusko** [comment]
I'm closing the issue due to inactivity. If you find new bug - don't hesitate to open new issues 😊 

Thank you for your contribution!
