### ISSUE TITLE
Animations with KeyboardAwareScrollView have poor performance on iOS release

### ISSUE THREAD

**Issue by Moreno97** [kirillzyusko/react-native-keyboard-controller#422]
**Describe the bug**
Animations with KeyboardAwareScrollView have poor performance on iOS release.

**Code snippet**
```ts
    <>
      <KeyboardAwareScrollView
        testID="keyboard-aware-scroll-view"
        keyboardShouldPersistTaps="handled"
        contentContainerStyle={{
               flexGrow: 1,
               padding: 16,
               backgroundColor: 'white',
        }}
        keyboardDismissMode="on-drag"
      >
      <View style={{ flex: 1 }}
       ...
      </View>
    </>
```

**To Reproduce**
Have an input and focus. I we have some buttons at the bottom, when placing at the top, animations are laggy.

**Expected behavior**
Animations shouldn´t be laggy and perfomance as 60/120 fps depending on device.

**Screenshots**

*Release:*

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/17690283/e35b4b0b-c9da-43c8-876f-f0745700bfda

*Debug:*

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/17690283/1472a29e-aaeb-4938-80b6-ca6787145f28

**Smartphone (please complete the following information):**

- Device: iPhone 14 Pro (seems to happen on all iOS devices)
- OS: iOS 17.4.1
- RN version: 0.73.5
- RN architecture: Old
- JS engine: Hermes
- Library version: **1.11.6**

**Additional context**
Seems to happen only on iOS devices and release flavour. On debug, everything is working fine 👍🏻 .

**Comment by kirillzyusko** [comment]
Hello @Moreno97 

Would you mind to attach `debug` video as well so that I can compare two of them and have a better understanding of where performance drop happens?

**Comment by Moreno97** [comment]
> Hello @Moreno97
> 
> Would you mind to attach `debug` video as well so that I can compare two of them and have a better understanding of where performance drop happens?

Sure, is attached now 👍🏻 , thanks. Seems that is not noticiable on the video, but it works way better on Simulator than Release flavour on real device.

**Comment by kirillzyusko** [comment]
> Sure, is attached now 👍🏻 , thanks. Seems that is not noticiable on the video, but it works way better on Simulator than Release flavour on real device.

Interesting, I'll have a look into it.

But may I ask you to try to comment out [this](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/ios/views/KeyboardControllerViewManager.swift#L112) line and see if it improves situation?

**Comment by Moreno97** [comment]
> > Sure, is attached now 👍🏻 , thanks. Seems that is not noticiable on the video, but it works way better on Simulator than Release flavour on real device.
> 
> Interesting, I'll have a look into it.
> 
> But may I ask you to try to comment out [this](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/ios/views/KeyboardControllerViewManager.swift#L112) line and see if it improves situation?

I can try it building the app release on my device. I'll try it and update as soon as I can.
Thanks 🙂.

**Comment by Moreno97** [comment]
> @Moreno97 potentially it can be fixed in #412
> 
> Can you try to install a library from latest `main` and check if it works better or not? 👀

Hello! I'll try as soon as possible.
Thanks! And KUDOS!

**Comment by Moreno97** [comment]
@kirillzyusko installing the library from `main` seems to be working better on real device!! At least, animations are less laggy and now are "pretty almost native and at full speed".
Thanks!! To me, we can close the issue <3.

**Comment by kirillzyusko** [comment]
@Moreno97 yoohoo 🎉 Thank you for the report and testing! 😊 

There is still some room for further improvements, so I'm going to make them even better/smoother/precise, but I'll do it slightly later 👀
