### ISSUE TITLE
Error: Exception in HostFunction: expected 1 arguments, got 0

### ISSUE THREAD

**Issue by edapess** [kirillzyusko/react-native-keyboard-controller#429]
**Describe the bug**
App crashes after start

**To Reproduce**
Update react native to 0.74.0

**Screenshots**
![Screenshot_1714466258](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/47182987/91f6117c-bbf8-49a2-8eaf-039465191ead)

<img width="1435" alt="Screenshot 2024-04-30 at 12 38 47" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/47182987/88d50ca4-bee0-4b7b-978d-06b38b6bab7e">

**Smartphone (please complete the following information):**

- Desktop OS: Mac OS 14.4.1
- Device: Pixel 8
- OS: Android
- RN version: 0.74.0
- JS engine: Hermes
- Library version: ^1.11.7

**Comment by edapess** [comment]
@kirillzyusko  is there any eta for react native  0.74 ?

**Comment by kirillzyusko** [comment]
Hello @edapess 

I was working in this branch for support 0.74 - https://github.com/kirillzyusko/react-native-keyboard-controller/pull/410/files

And I managed to run both apps (paper/fabric) without significant code modifications 🤷‍♂️ Can you try to use the version from this branch and see if it fixes the problem?

**Comment by edapess** [comment]
@kirillzyusko you mean `react-native : "0.74.0-rc.6"` ?

**Comment by kirillzyusko** [comment]
@edapess I meant to try to use `chore/react-native-0.74` branch and install `react-native-keyboard-controller` from github (instead of `npm`).

**Comment by edapess** [comment]
@kirillzyusko I tried but it's not working, I think the issue can be related to reanimated version that we have to use in our app.

`"react-native-reanimated": "^3.9.0",`

**Comment by kirillzyusko** [comment]
Yes @edapess 

Can you try to use a version from the PR you sent? In this PR I'm using REA 3.9.0 so we both should use the same version 😊

**Comment by edapess** [comment]
@kirillzyusko I tried again, nothing changed, so the error comes from 

<img width="1198" alt="Screenshot 2024-04-30 at 19 09 23" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/47182987/dada93c3-e4bd-4a33-bd29-cddcc479c981">

<img width="300" alt="Screenshot 2024-04-30 at 19 09 23" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/47182987/3a6630fe-6b04-401f-bbe2-63f0f4841795">

**Comment by kirillzyusko** [comment]
Interesting 🤔 What is the version of REA in `react-native-keyboard-controller/node_modules/react-native-reanimated`?

**Comment by edapess** [comment]
it's `3.9.0`


I found another thing, here is [comment](https://github.com/software-mansion/react-native-reanimated/issues/5928#issuecomment-2078798759)

her is [issue ](https://github.com/software-mansion/react-native-reanimated/issues/5928)

**Comment by kirillzyusko** [comment]
@edapess it's weird 🤔 Why everything works in my PR? I'm also using `bottom-sheet` and `safe-area-context` in my example app.

**Comment by edapess** [comment]
@kirillzyusko yeeeah, it's weird :////, there is many reports

**Comment by edapess** [comment]
@kirillzyusko Thanks anyway, will try, and will get back here if i find something, maybe it will help somebody else

**Comment by irekrog** [comment]
Sometimes I get exactly this error, but in React Native 0.73 and reanimated 3.8 and latest version keyboard-controller. It's hard to say what's wrong because the error appears randomly, only on Android.

**Comment by edapess** [comment]
Hey @irekrog @kirillzyusko I found the problem, in our app we had reanimated in resolutions section, so there was 3.6.1 version, which causes the problem, so check that case. Hope this will help you. So now my reanimated is 3.9.0 and react native is 0.74.0, everything works fine

**Comment by irekrog** [comment]
FYI in my case there was a problem with react-native-code-push :)

**Comment by kirillzyusko** [comment]
@edapess cool, glad we figured out and resolved your problems 😊 I'll close the issue then!
