### ISSUE TITLE
KeyboardAwareScrollView not work with text input in nested ScrollView

### ISSUE THREAD

**Issue by kiethuynh0904** [kirillzyusko/react-native-keyboard-controller#442]
Thank you for creating an awesome library. However, I have a specific case and was wondering if you could take a look and help me out?
**Describe the bug**
The KeyboardAwareScrollView does not work with nested ScrollView, Is there any specific way I can make it work?

**The code looks like**
![Nested Scrollview (1)](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/80958695/89af0693-e2fd-453d-bd1f-87b1ef2850ca)

**Comment by kirillzyusko** [comment]
Hello @kiethuynh0904 

Can you check if https://github.com/kirillzyusko/react-native-keyboard-controller/pull/443 fixes the problem?

**Comment by kiethuynh0904** [comment]
Hi @kirillzyusko thanks for the quick reply. It works like a charm!

**Comment by kirillzyusko** [comment]
@kiethuynh0904 awesome! I'll merge it to `main` and will publish under `1.12.1` tag (though I don't have an exact dates when I publish a new release). In a meantime you can patch it using `patch-package` 👀
