### ISSUE TITLE
This library will support the Flutter version

### ISSUE THREAD

**Issue by vera-byte** [kirillzyusko/react-native-keyboard-controller#458]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vera-byte** [comment]
https://github.com/kirillzyusko/react-native-keyboard-controller/assets/42960387/679a8915-ebbd-4c85-9cf8-3a7c97ed1b6a


https://github.com/kirillzyusko/react-native-keyboard-controller/assets/42960387/a99bdf48-5ca3-40e7-8d55-f016a85b3fb3

Video 1 was developed by Flutter App. When the keyboard is raised, there is always a certain delay in the input box.
In video 2, react-native-keyboard-controller is used, which is comparable to native

The above is the problem I encountered

**Comment by vera-byte** [comment]
I found many plug-ins on Flutter Pub but failed to solve this problem. However, with the help of netizens, react-native-keyboard-controller was provided.

**Comment by kirillzyusko** [comment]
@vera-byte for a `keyboard-controller` - which hook did you use for implementation? Can you share a small code sample that you used in your implementation? Asking because of this depends my further answer 👀

**Comment by kirillzyusko** [comment]
@vera-byte But basically - `useKeyboardAnimation`/`useReanimatedKeyboardAnimation` depends on default iOS implementation, and since RN renders truly native views -> animations are also managed by OS and because of that everything runs super smooth and synchronized.

From the other side Flutter renders everything on a pixel level (via Skia engine) and it has to perform animations on its own. And for that you have to synchronize keyboard animation and flutter animation and it's pretty challenging task 😔 

Do you use latest version of Flutter? I remember they recently (I think a year ago 😅) made a lot of improvements.

**Comment by vera-byte** [comment]
> @vera-byte但基本上 - `useKeyboardAnimation`/`useReanimatedKeyboardAnimation`取决于默认的 iOS 实现，并且由于 RN 渲染真正的原生视图 -> 动画也由 OS 管理，因此一切都运行得非常流畅和同步。
> 
> 另一方面，Flutter 在像素级别渲染所有内容（通过 Skia 引擎），并且必须自行执行动画。为此，您必须同步键盘动画和 Flutter 动画，这是一项非常具有挑战性的任务 😔
> 
> 你使用最新版本的 Flutter 吗？我记得他们最近（我想是一年前 😅）做了很多改进。

<img width="572" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/42960387/41c9b732-f039-41ea-8463-e4d71d8f0ee0">

This is the version of FLutter I am currently using

**Comment by vera-byte** [comment]
> @vera-byte您指的是输入框和实际键盘位置之间的延迟吗（比如输入框总是在键盘前面，对吗）？
> 
> <img alt="图像" width="687" src="https://private-user-images.githubusercontent.com/22820318/335540819-73a3a370-2941-4d3e-8a8a-8ccb4581fa2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTA5ODEsIm5iZiI6MTcxNzE1MDY4MSwicGF0aCI6Ii8yMjgyMDMxOC8zMzU1NDA4MTktNzNhM2EzNzAtMjk0MS00ZDNlLThhOGEtOGNjYjQ1ODFmYTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDEwMTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMGZiZTE1NmJkMmQ2ODg0YjkxNzBkZGI1NGNmMzQ1NWIxZmU4MDA3Y2I5ZTIxMmIxNjI3MGMwN2RmOWI0NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZXHSCQxjcPDfgY8DY1zkeL5d-AgdEAnb8eSX2SmlEoU">
> 对于`keyboard-controller`- 您使用了哪个钩子来实现？您可以分享一下您在实现中使用的小代码示例吗？因为这个而问的问题取决于我的进一步回答👀


Example Code 


import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final FocusNode _focusNode = FocusNode();
  bool visible = false;

  void _visible() {
    setState(() {
      print("之行");
      visible = !visible;
      _focusNode.unfocus();
    });
  }

  @override
  void initState() {
    super.initState();
    _focusNode.addListener(_onFocusChange);
  }

  void _onFocusChange() {
    if (_focusNode.hasFocus) {
      setState(() {
        visible = false;
      });
    }
  }

  @override
  void dispose() {
    _focusNode.removeListener(_onFocusChange);
    _focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Column(
        children: [
          Expanded(
            child: ListView(
              children: List.generate(40, (index) => const Text("data")),
            ),
          ),
          SafeArea(
            child: Column(
              children: [
                Row(
                  children: [
                    IconButton(
                      onPressed: _visible,
                      icon: const Icon(Icons.image),
                    ),
                    Expanded(
                      child: TextField(
                        focusNode: _focusNode,
                      ),
                    ),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: List.generate(
                    6,
                    (index) => TextButton(
                      onPressed: () {},
                      child: Text("按钮$index"),
                    ),
                  ),
                ),
                // ClipRect(
                //   child: AnimatedContainer(
                //     curve: Curves.bounceIn,
                //     duration: const Duration(milliseconds: 300),
                //     height: visible ? 200.0 : 0.0,
                //     color: Colors.green,
                //     // 在这里添加你的额外内容或子 Widget
                //   ),
                // ),
                AnimatedContainer(
                  curve: Curves.easeOutQuint,
                  duration: const Duration(milliseconds: 500),
                  height: visible ? 300.0 : 0,
                  color: Colors.green,
                  // 添加你的子 Widget
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

**Comment by kirillzyusko** [comment]
> import 'package:flutter/material.dart';

@vera-byte I was asking about `react-native-keyboard-controller` code (for the second video) 🙈

**Comment by kirillzyusko** [comment]
@vera-byte I'm going to close that issue, because the answer on the original question - "No, I'm not planning to add a support for Flutter in a near future".

However feel free to share additional code samples from `keyboard-controller` project - I'll be happy to answer on your questions and difference between `flutter`/`react-native` 🙌 😊
