### ISSUE TITLE
When focusing for the first time, the onSelectionChange of useFocusedInputHandler is not called

### ISSUE THREAD

**Issue by zyslife** [kirillzyusko/react-native-keyboard-controller#482]
**Describe the bug**
"When focusing for the first time, the onSelectionChange of useFocusedInputHandler is not called, but the native onSelectionChange is called. An example that can reproduce this issue: FocusedInputHandlers."

**To Reproduce**

1.First, enter 𝑛 characters in the input field. At this point, the cursor is at the end.
2.Make the input field lose focus.
3.Click at the beginning of the input field, causing the cursor to focus on the first character.
4.The onSelectionChange of useFocusedInputHandler will not be called.

**Expected behavior**
My expected behavior: it should be called just like the native onSelectionChange, because this is very important; otherwise, the cursor position will be incorrect.

**Comment by zyslife** [comment]
That was a fast fix, thumbs up~ I hope it keeps getting better and better.

**Comment by kirillzyusko** [comment]
Thanks @zyslife ❤️ 

I'll test code changes again tomorrow and if everything is okay, then will merge them 👀 In a meantime you can use `patch-package` to fix it in your project 🤞
