### ISSUE TITLE
Limited Items Displayed in KeyboardAwareScrollView with FlashList

### ISSUE THREAD

**Issue by AradSharafi** [kirillzyusko/react-native-keyboard-controller#497]
**Describe the bug**
When using the KeyboardAwareScrollView component in conjunction with FlashList, only a subset of the total items is displayed. For instance, if there are 100 items, only the first 30 items are rendered instead of all 100. By the way I pass KeyboardAwareScrollView to renderScrollComponent prop.

**Code snippet**
```
import React from 'react';
import { View, Text } from 'react-native';
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';
import { FlashList } from '@shopify/flash-list';

const items = Array.from({ length: 100 }, (_, index) => `Item ${index + 1}`);

const MyComponent = () => {
  return (
    <View>
      <FlashList
        data={items}
        renderItem={({ item }) => (
          <View style={{ height: 50, borderBottomWidth: 1, borderBottomColor: '#ccc' }}>
            <Text>{item}</Text>
          </View>
        )}
        estimatedItemSize={50}
         renderScrollComponent={(props) => (
          <KeyboardAwareScrollView {...props} />
        )}
      />
    </View>
  );
};

export default MyComponent;
```

**Expected behavior**
All 100 items should be displayed within the FlashList when scrolling through the list. The KeyboardAwareScrollView should handle keyboard events appropriately without interfering with the rendering of all items in the FlashList.

**Screenshots**
https://github.com/kirillzyusko/react-native-keyboard-controller/assets/88803340/933812c6-9a04-4a73-8e79-869af83ce74c

**Smartphone (please complete the following information):**

- Desktop OS: MacOS Sonoma 14.3
- Device: iPhone Xs
- OS: 17.2
- Expo version: 51.0.17 
- RN version: 0.74.2
- RN architecture: old 
- JS engine: Hermes
- Library version: 1.11.4

**Comment by kirillzyusko** [comment]
@AradSharafi why do you use `KeyboardAwareScrollView` from `react-native-keyboard-aware-scroll-view`?

This code snippet works fine in my example app:

```tsx
import React from 'react';
import { View, Text } from 'react-native';
import { KeyboardAwareScrollView } from 'react-native-keyboard-controller';
import { FlashList } from '@shopify/flash-list';

const items = Array.from({ length: 100 }, (_, index) => `Item ${index + 1}`);

const MyComponent = () => {
  return (
    <View style={{ flex: 1 }}>
      <FlashList
        data={items}
        renderItem={({ item }) => (
          <View style={{ height: 50, borderBottomWidth: 1, borderBottomColor: '#ccc' }}>
            <Text>{item}</Text>
          </View>
        )}
        estimatedItemSize={50}
         renderScrollComponent={(props) => (
          <KeyboardAwareScrollView {...props} />
        )}
      />
    </View>
  );
};

export default MyComponent;
```

<img src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/34e8b712-c080-40b5-9439-573da77fc499" height="600">

**Comment by AradSharafi** [comment]
Oh Sorry my bad. You're right about react-native-keyboard-aware-scroll-view. 

but it remains the bug for me.

**Comment by kirillzyusko** [comment]
@AradSharafi I'm using the 1.12.5 version - can you try this one? If the bug remains, then please, create a reproduction example because I cannot reproduce this problem in my example app

**Comment by AradSharafi** [comment]
@kirillzyusko I tried the 1.12.5 version and a new error has arisen.

I just updated and didn't change anything.


<img src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/88803340/c11905c2-2f5c-4351-a447-2bcd8ed960ab" alt="description" width="200" />

**Comment by kirillzyusko** [comment]
@AradSharafi I can not help here as I haven't seen a similar error in my project 🤷‍♂️ Please, create a reproduction example 🙏

**Comment by kirillzyusko** [comment]
@AradSharafi may I know the status of the issue? Did you try `1.11.6` version? Did it solve the problem for you?

**Comment by AradSharafi** [comment]
Hi @kirillzyusko,

Apologies for the delay in getting back to you. I finally had a chance to test the issue with version 1.11.6.

Voila! It works perfectly now. Thank you for the update. I'll close it down.

By the way, I do appreciate you. Your library is awesome and valuable ❤
