### ISSUE TITLE
KeyboardAwareScrollView not figuring style or contentContainerStyle (IOS & Android)

### ISSUE THREAD

**Issue by TimeForRelax** [kirillzyusko/react-native-keyboard-controller#504]
this is example how I'm using it. Issue here - KeyboardAwareScrollView can't read style or contentContainerStyle properties. I tried flex: 1, gap: moderateScale{from 'react-native-size-matters'}(value), I tried only values like 20, 120 for paddingBottom, also tried Math.round etc. In all cases I facing with one error

```
const paddingBottom = Math.round(bottom + moderateScale(60))

  return (
    <View style={[styles.wrapper, { backgroundColor: theme("white") }]}>
      <HeaderScreen
        type={headerScreenIconType}
        title={title}
      />

      <KeyboardAwareScrollView
        // style={localeStyles.scrollView}
        contentContainerStyle={{ paddingBottom }}
        // extraKeyboardSpace={moderateScale(60)}
        bottomOffset={moderateScale(20)}>
        {children}
      </KeyboardAwareScrollView>

      <CustomButton
        loading={buttonIsLoading}
        onPress={onSavePress}
        text="Save changes"
        style={[styles.saveButton, { bottom: bottom }]}
      />
    </View>
  )
}

const localeStyles = StyleSheet.create({
  scrollView: {
    flexGrow: 1,
  },
  // scrollViewContainer: {
  //   gap: moderateScale(15),
  // },
})

```

without any styles it working very well. for importing styles I tried 2 variants: locale styles and import from file.

1. add KeyboardAwareScrollView
2. add some style or contentContainerStyle with any value like flex or paddingBottom.
3. enjoy error

![image](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/143207024/75094966-b77e-4e43-8e0c-711cefe42001)

![image](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/143207024/ccf09371-83e8-4fea-b21b-1286480c97ed)

Devices: 
Iphone 15 Pro, Mi Note 10 Lite (real devices)

**Comment by TimeForRelax** [comment]
"dependencies": {
    "@gorhom/bottom-sheet": "^5.0.0-alpha.10",
    "@gorhom/portal": "^1.0.14",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "react": "18.2.0",
    "react-native": "0.74.1",
    "react-native-blob-util": "^0.19.9",
    "react-native-keyboard-controller": "^1.12.5",
    "react-native-reanimated": "^3.11.0",
    "react-native-safe-area-context": "^4.10.1",
    "react-native-screens": "^3.31.1",
    "react-native-size-matters": "^0.4.2",
  },

**Comment by kirillzyusko** [comment]
@TimeForRelax what is the version of `react-native-reanimated` is in the `(yarn.lock|package-lock.json)` file? I see it's 3.11.0 in package, but what is the exact version in lock file? 👀

**Comment by TimeForRelax** [comment]
> @TimeForRelax what is the version of `react-native-reanimated` is in the `(yarn.lock|package-lock.json)` file? I see it's 3.11.0 in package, but what is the exact version in lock file? 👀

the same one. ^3.11.0

**Comment by kirillzyusko** [comment]
>  I am using 3.12.0, but the issue from react-native-reanimated solved in 3.12.1

Yep. Can you try to upgrade the version and see if the problem gets resolved? 👀

**Comment by TimeForRelax** [comment]
sure, reinstalling deps...

**Comment by TimeForRelax** [comment]
maybe you all can help me with this issue?)https://github.com/gorhom/react-native-bottom-sheet/issues/1883

**Comment by TimeForRelax** [comment]
did you get same trouble?

**Comment by kirillzyusko** [comment]
> maybe you all can help me with this issue?)https://github.com/gorhom/react-native-bottom-sheet/issues/1883

Unfortunately not 😓 I'm not working closely with `bottom-sheet` so can't say what exactly happens there at quick glance 🤷‍♂️

**Comment by TimeForRelax** [comment]
Great support! Thx. Its working now with react-native-reanimated: '3.12.1'

**Comment by TimeForRelax** [comment]
> > maybe you all can help me with this issue?)[gorhom/react-native-bottom-sheet#1883](https://github.com/gorhom/react-native-bottom-sheet/issues/1883)
> 
> Unfortunately not 😓 I'm not working closely with `bottom-sheet` so can't say what exactly happens there at quick glance 🤷‍♂️

Hey, are you here? can you help with case when i wnat press clearButton in my customInput, but KeyboardAwareScrollView hiding Keyboard?

**Comment by TimeForRelax** [comment]
![image](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/143207024/9e91800c-dd86-496f-af21-d33a8e16ab86)

**Comment by kirillzyusko** [comment]
@TimeForRelax will it help https://github.com/kirillzyusko/react-native-keyboard-controller/discussions/360#discussioncomment-8502972?

**Comment by TimeForRelax** [comment]
nope(

**Comment by TimeForRelax** [comment]
I believe that problem here is that TextInput not covered clearButton. TextInput have paddingRight like 45 and clearButton its just TouchableOpacity. But I want KeyboardDismiss only if I tap outside Block with textInput & clearButton

**Comment by TimeForRelax** [comment]
![image](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/143207024/51636bbe-371e-46ce-8e9f-25266360d01c)

**Comment by kirillzyusko** [comment]
Strange - in this case TouchableOpacity should intercept touch and don't propagate it further.

I would try to call `e.preventDefault()` and verify that `TouchableOpacity`, `ScrollView` and other components come from `react-native` package (not a combination of `react-native-gesture-handler`)...

**Comment by TimeForRelax** [comment]
I am using all Components from react-native and I am not using ScrollView, I just using your KeyboardAwareScrollView

**Comment by TimeForRelax** [comment]
OOOOOH SHIT!!! I know what the problem???? AHAHHA

TouchableOpacity was small for finger, its causing the behavior that hard to snipe this button))))

Will add hitslop!

**Comment by TimeForRelax** [comment]
![image](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/143207024/267d6777-709a-495e-bebe-31c02aa1ad83)
