### ISSUE TITLE
Error preventing navigation

### ISSUE THREAD

**Issue by Code-Victor** [kirillzyusko/react-native-keyboard-controller#525]
**Describe the bug**
The package works well but when I press the back button to go to a previous page, this error Occurs

**Code snippet**
```tsx
<Animated.FlatList
        ref={flatListRef}
        data={options}
        itemLayoutAnimation={ListLayoutTransition}
        renderScrollComponent={(props) => (
          <KeyboardAwareScrollView bottomOffset={12} {...props} />
        )}
        refreshControl={
          props.actionType === "edit" && isLoadingFlashcard ? (
            <RefreshControl
              refreshing={isLoadingFlashcard}
              colors={[color.primary]}
            />
          ) : undefined
        }
        ListHeaderComponent={() => (
          <View mb="$6">
            <ControlledInput
              control={control}
              variant="outline"
              name="name"
              label="Name of flashcard"
            />
          </View>
        )}
        ItemSeparatorComponent={() => <View h={24} />}
        ListFooterComponent={() => (
          <XStack jc="flex-end" pt="$2">
            <Button
              icon={
                <MaterialIcons
                  name="add"
                  size={24}
                  color={getTokenValue("$color.blue")}
                />
              }
              onPress={addNewQuestion}
              size="$3"
              rounded="sm"
              type="ghost"
              fontFamily="$hurmeGeometricSans2"
              color="$blue"
            >
              Add card
            </Button>
          </XStack>
        )}
        keyExtractor={(item) => item.id}
        renderItem={renderItem}
        keyboardShouldPersistTaps="handled"
        contentContainerStyle={styles.listContainer}
      />
```
> [!NOTE]
> I already added the `KeyboardProvider` 

**To Reproduce**
1. Create a list of inputs
2. click on the input
3. dismiss with the back button.
4. press the back button again
5. 
**Expected behavior**
it should allow the back button pressed

**Screenshots**
![WhatsApp Image 2024-07-29 at 01 11 07_342bd5df](https://github.com/user-attachments/assets/179b1880-e41d-4a1a-a6e2-3994b92890dc)

**Smartphone (please complete the following information):**
Redmi Note 12

System:
- Library version: ^1.12.7
  OS: Windows 11 10.0.22631
  CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Memory: 3.40 GB / 19.85 GB
Binaries:
  Node:
    version: 18.19.0
    path: ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
  Yarn:
    version: 3.6.4
    path: ~\scoop\apps\yarn\current\bin\yarn.CMD
  npm:
    version: 10.2.3
    path: ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowAllTrustedApps: Disabled
    Versions:
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.7.34202.233 (Visual Studio Community 2022)
Languages:
  Java:
    version: 17.0.11
    path: /c/Program Files/Microsoft/jdk-17.0.11.9-hotspot/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Additional context**

**Comment by kirillzyusko** [comment]
@Code-Victor does the problem happens because of the usage of Layout Animation? have you tried to remove them and check if it works?

Can you also post a full minimal reproduction demo? So that I can clone the project on my computer and play around the code?

**Comment by Code-Victor** [comment]
I tried removing the layout animation but it didn't work.
Finally, I tried removing the ref and it works, but I don't know why it worked.

I'll make sure to create a reproduction demo ASAP.

Thanks for your time and support @kirillzyusko

**Comment by Code-Victor** [comment]
@kirillzyusko Here is the reproduction.
https://github.com/Code-Victor/rnkc-error-reproduction

I created a dev build already so you can use this to make it fast. https://expo.dev/accounts/oluwaborihamzat/projects/rnkc-error-reproduction/builds/7018fd7c-1091-4413-bd6d-f7c2a57d6aa0

Thanks

**Comment by kirillzyusko** [comment]
Thanks @Code-Victor ❤️ 

I'll try to look into the code and figure out what is going wrong. Thank you for providing a repo for reproduction! 😎

**Comment by kirillzyusko** [comment]
@Code-Victor as a workaround you can use:

```tsx
<Animated.FlatList
  ref={(ref) => {
    if (ref) {
      flatListRef.current = ref;
    }
  }}
// ...
/>
```

And in a meantime I'll try to find a proper solution or discover a root cause 👍

**Comment by kirillzyusko** [comment]
@Code-Victor here is the fix: https://github.com/kirillzyusko/react-native-keyboard-controller/pull/527

Would you mind to check it and let me know if it fixes the problem for you or not?

**Comment by Code-Victor** [comment]
Thanks @kirillzyusko 
Yes, I'd love to test it out.

**Comment by Code-Victor** [comment]
It now works!

Thanks so much for your help I appreciate it🫡

**Comment by kirillzyusko** [comment]
Thank you @Code-Victor for providing reproduction example and for your quick responses ❤️ 

I merged this fix, but don't know when I publish a new version (I was planning to publish `1.13.0`, because made some important changes to modals handling on Android). So in a meantime you can apply a patch (using `patch-package`) in your project 🙂 And later on you can upgrade to newest version!
