### ISSUE TITLE
when importing KeyboardProvider error

### ISSUE THREAD

**Issue by dsagredo** [kirillzyusko/react-native-keyboard-controller#535]
I installed the library and a

![Captura de pantalla 2024-08-04 a la(s) 19 19 00](https://github.com/user-attachments/assets/585c3943-e47a-40fb-902e-eb8fb349d449)

When I run the app every things work than I try to import the KeyboardProvider and I get this error

App.tsx
```
import React from 'react';
import {
  KeyboardAwareScrollView,
  KeyboardProvider,
} from 'react-native-keyboard-controller';
import {View, Text, TextInput} from 'react-native';

const App = () => {
  return (
    <KeyboardProvider>
      <KeyboardAwareScrollView>
        <View style={{height: 800, backgroundColor: 'lightblue'}} />
        <Text>Input:</Text>
        <TextInput
          style={{
            height: 44,
            borderStyle: 'solid',
            borderWidth: 1,
            borderColor: 'black',
          }}
          autoComplete="email" // or textContentType="emailAddress"
        />
        <View style={{height: 800, backgroundColor: 'lightblue'}} />
      </KeyboardAwareScrollView>
    </KeyboardProvider>
  );
};

export default App;
```

To Reproduce
npm install react-native-keyboard-controller and react-native-reanimated
pod install
run ios
import KeyboardProvider

**Comment by kirillzyusko** [comment]
Hey @dsagredo 

Did you add a reanimated plugin to the babel plugin list and restarted the metro server with the `--reset-cache` option?

**Comment by dsagredo** [comment]
> Hey @dsagredo
> 
> Did you add a reanimated plugin to the babel plugin list and restarted the metro server with the `--reset-cache` option?

Thanks you! close.
