### ISSUE TITLE
Failing for even a minimal attempt

### ISSUE THREAD

**Issue by useEffects** [kirillzyusko/react-native-keyboard-controller#545]
```tsx
import { StatusBar } from 'expo-status-bar';
import { FlatList, StyleSheet, Text, TextInput, View } from 'react-native';
import { KeyboardProvider, KeyboardAwareScrollView } from "react-native-keyboard-controller";

const data = Array.from({ length: 100 }).map(_ => "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, eveniet.")

export default function App() {
  return <KeyboardProvider>
    <View style={{ flex: 1 }}>
      <FlatList
        data={data}
        renderItem={({ item }) => <Text>{item}</Text>}
        renderScrollComponent={props => <KeyboardAwareScrollView {...props} />}
      />
      <TextInput />
    </View>
  </KeyboardProvider>
}
```

![image](https://github.com/user-attachments/assets/2d363e79-82f9-4767-9d52-e38c8dce380c)

**Comment by kirillzyusko** [comment]
I think it's because you embed your `TextInput` outside of `KeyboardAwareScrollView`, right?

In your case I believe you should use `KeyboardAvoidingView` instead of `View` and it should work.

Let me know if it doesn't 🙏

**Comment by useEffects** [comment]
Yes, if the `TextInput` are inside `KeyboardAwareScrollView`, it works perfectly fine. For my case, I have no other choice but to use a `KeyboardAvoidingView`

**Comment by kirillzyusko** [comment]
@useEffects you may also consider using the `KeyboardStickyView` component for sticky `TextInput`.

Or if you are building a chat-like app, then you can clone an example app to see advanced examples on how to use library primitives to deliver the best possible experience to the user (like interactive keyboard or just to see how to build simple UI for chat-like apps using functionality of this library) 😊
