### ISSUE TITLE
useKeyboardAnimation doesn't work on Samsung Galaxy Note 20

### ISSUE THREAD

**Issue by fobos531** [kirillzyusko/react-native-keyboard-controller#55]
**Describe the bug**
I suppose the keyboard height values aren't exposed to the hook correctly on Samsung Galaxy Note 20. Something's probably wrong with keyboard height events there

**Repo for reproducing**
Simply use the example app from this repo - the key is running the app on a Samsung Galaxy Note 20.

**Expected behavior**
Keyboard height values should be correctly exposed to the useKeyboardAnimation hook on Samsung Galaxy Note 20

**Screenshots**
[![CleanShot 2022-08-18 at 00 09 53](https://user-images.githubusercontent.com/19533289/185252314-1b941591-4582-4d99-98ff-bceebd09dfe4.png)](https://share.cleanshot.com/w5MvIj) Under the keyboard - there are two inputs. The keyboard height values are being correctly returned for other Samsung Galaxy devices, like the Galaxy S21. It's the Galaxy Note 20 that is problematic.

**Smartphone (please complete the following information):**
 - Desktop OS: MacOS Ventura 
 - Device: Samsung Galaxy Note 20
 - OS: Android 10 & Android 12
 - JS engine Hermes
 - Library version Latest

**Additional context:**
It seems its something specific to Galaxy Note 20 (since it works on other Samsung devices), but I'm not sure what that would be.

**Comment by kirillzyusko** [comment]
Hi @fobos531 

It's really interesting why it doesn't work on Galaxy Note 20 🤔 
Anyway, I will try to reproduce the problem using Samsung [Remote Test Lab](https://developer.samsung.com/remote-test-lab) - I don't have a physical device, so I have to rely only on it.
Hopefully it will be reproducible there and I can figure out what's the problem.

If you could reproduce it on any simulators (Android Studio/Genymotion) - let me know :)

**Comment by fobos531** [comment]
Hey, thank you very much for looking into it! Yeah, unfortunately I also don't have this device so I had to rely on Browserstack's service to reproduce this bug - but if there's anything else I can do, let me know, I'm happy to help!

**Comment by kirillzyusko** [comment]
@fobos531 never heard about Browserstack🤔 Is it publicly available (i. e. I can sign up and get a remote device for testing?). And if yes - is it free?

**Comment by fobos531** [comment]
> @fobos531 never heard about Browserstack🤔 Is it publicly available (i. e. I can sign up and get a remote device for testing?). And if yes - is it free?

Their remote device testing service is called App Live. Unfortunately it doesn't looks there is a fully free plan: https://www.browserstack.com/accounts/subscriptions?product=app-live

**Comment by kirillzyusko** [comment]
Hi @fobos531 
Just letting you know, that I've tested example app on Note 20 (Android 11) and it works good:

https://user-images.githubusercontent.com/22820318/185419741-ee6c16b5-8946-4115-9c70-61ee5974e36b.mov

I know, that you've tested it on Android 10 & 12, so it may be the issue. Anyway I will try to catch a time point where more devices will be available (and hopefully I can reproduce the problem) 🤞

**Comment by kirillzyusko** [comment]
`Note 20` (with Android 10/12) is still not available so I decided to test it on `Note 20 Ultra` (Android 12) - still works good:

https://user-images.githubusercontent.com/22820318/185568361-83c5bd33-a6c7-4621-ae63-a048e6573bd2.mov

**Comment by kirillzyusko** [comment]
@fobos531 just tested it on Note20 Android 12 - still, everything works fine 🤷‍♂️ 

https://user-images.githubusercontent.com/22820318/186109058-245fc79e-7e8d-475f-8163-9725ae5a1ff6.mov

I ran app from `main` branch (it uses RN 0.69). Would you mind to run `example` app from `main` branch on your device?
Because I can not reproduce the issue and I don't understand where the problem is 😔

**Comment by fobos531** [comment]
Hmm, if it works fine for you, maybe it's something related to my setup - I'll hopefully check it out when I have some time to do so, I'm currently swamped with work. Until then, I'll close this issue. Once again, thank you for the effort put into this issue! 🙌
