### ISSUE TITLE
Add information about useReanimatedKeyboardAnimation in installation instructions

### ISSUE THREAD

**Issue by kapir** [kirillzyusko/react-native-keyboard-controller#561]
**Is your feature request related to a problem? Please describe.**
We where experiencing an issue where the useAnimatedKeyboard from reanimated was reporting wrong values, usually that the height was not set to 0 after we do a heavy render while closing the keyboard.

The fix was to switch to the useReanimatedKeyboardAnimation from this library

**Describe the solution you'd like**
As long as my assumption is right that this library is not just reexporting the useAnimatedKeyboard hook from reanimated:

We where already using reanimated when adding this library, adding that we should switch the hook would be a nice addition to the documentation.

**Comment by kirillzyusko** [comment]
Hey @kapir 👋 

You are right, this library doesn't re-export `useAnimatedKeyboard` from reanimated 🙂 

This library heavily relies on worklet/etc. concept coming from reanimated and using these concepts brings advanced tools to keyboard handling. But I'm using my own keyboard tracking solution.

Where you would like to see a note about that? And maybe you would like to see some kind of comparison between functionality of this library and hook from reanimated?

I think it would be definitely good to mention the difference between reanimated and this library 😊

**Comment by kirillzyusko** [comment]
> Does the keyboard controller library effect the useAnimatedKeyboard hook from reanimated? 

@kapir on iOS both hooks from `reanimated` and `keyboard-controller` should work simultaneously. On Android I'm not sure - potentially two hooks can conflict with each other.
Which platform did you test? What is the error do you see? Which keyboard-controller and reanimated version do you use?

> If yes, it could be mentioned in the installation instructions or the troubleshooting section. If no, I think it would be beneficial for the library to have a comparison with reanimated showcasing the benefits of using this instead of reanimated.

Okay, cool, I'll think on how and where to add the information.

**Comment by kapir** [comment]
Hi, sorry for lack of detail.

This was on ios:

We have a screen with a textinput and some list items. Pressing the listitem opens up a "complex" navigation screen containing some nestet navigators from react-navigation. Including a tab bar, we have a custom tab bar, that we hide with the keyboard height (translating positive) so that it is hidden when keyboard is visible. The option on the react-navigation tabbar has not worked very well for us, therefore this custom solution.

The issue was that sometimes (seemingly randomly) when pressing an list item, the keyboard would close, but the tabbar would jump (maybe 50 pixels up, then down, then disappear). It disappeared because the animated keyboard height would report as if the keyboard was open. The jumping still appear but the tabbar does no longer disappear.
If i would guess the reason for the jumping is that the render is a bit heavy slowing the listeners on the keyboard navigation down.

**Comment by kirillzyusko** [comment]
@kapir I updated documentation in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/567

Can you check [installation](https://kirillzyusko.github.io/react-native-keyboard-controller/pr-preview/pr-567/docs/installation#adding-a-library-to-the-project) and [comparison](https://kirillzyusko.github.io/react-native-keyboard-controller/pr-preview/pr-567/docs/recipes/architecture#what-is-the-difference-between-useanimatedkeyboard-from-react-native-reanimated-and-this-library) page?

**Comment by kapir** [comment]
This looks great, and further clarifies the differences, and the reason for it 👍

Great work 🤩

**Comment by kirillzyusko** [comment]
@kapir cool! I merged the PR! Thank you for raising this issue 🙌
