### ISSUE TITLE
 Require cycle

### ISSUE THREAD

**Issue by a-eid** [kirillzyusko/react-native-keyboard-controller#562]
**Describe the bug**

I noticed this require cycle warning on the latest RNKC version ^1.13.2
```bash
λ  WARN  Require cycle: ../../node_modules/react-native-keyboard-controller/lib/commonjs/index.js -> ../../node_modules/react-native-keyboard-controller/lib/commonjs/components/index.js -> ../../node_modules/react-native-keyboard-controller/lib/commonjs/components/KeyboardToolbar/index.js -> ../../node_modules/react-native-keyboard-controller/lib/commonjs/index.js
```

**Code snippet**
NA 

any imports would trigger this. 

**Repo for reproducing**
NA

**To Reproduce**
NA

**Expected behavior**
No require cycle warnings. 

**Screenshots**
<img width="776" alt="Screenshot 2024-08-22 at 9 24 31 PM" src="https://github.com/user-attachments/assets/7924298a-a78c-478b-8caa-5c19ee371be1">

**Comment by kirillzyusko** [comment]
Thank you for the report @a-eid 

I will try to fix it tomorrow!
