### ISSUE TITLE
useKeyboardHandler height onMove is not updated when switching to Emoji on iOS

### ISSUE THREAD

**Issue by kimak** [kirillzyusko/react-native-keyboard-controller#600]
**Describe the bug**
When switching the Keyboard in Emoji mode the height `useKeyboardHandler` onMove event is not updated.

**Code snippet**
```
  useKeyboardHandler(
    {
      onMove: (event) => {
        'worklet'
        height.value = Math.max(event.height, 0)
      },
    },
    []
  )
```

**Repo for reproducing**
Here a simple snack example https://snack.expo.dev/@kimak/keyboard-emoji
Let me know if you need a reproducible repo.

**To Reproduce**

1. Open the keyboard on iOS input
2. Switch the keyboard in emoji
3. The height is not updated

**Expected behavior**
When switching to emoji the height of the keyboard should update

**Screenshots**:
Working example
![Screenshot 2024-09-26 at 23 17 58](https://github.com/user-attachments/assets/60e0717d-1573-4911-8517-dc5f8d1210b2)

Issue
![Screenshot 2024-09-26 at 23 18 29](https://github.com/user-attachments/assets/79201c45-8d37-4618-b139-cf593e2b42ce)

**Smartphone (please complete the following information):**

- Device: iPhone SE
- OS: iOS 17
- RN version: 0.72
- JS engine: Hermes
- Library version: 1.3.4

**Comment by kirillzyusko** [comment]
@kimak the `onMove` handler is supposed to be called only during the animation frame. In your case the transition is instant and there are literally 0 animation frames, so `onMove` is not getting called.

To assure that shared value is always synchronized with keyboard position you should always use `onEnd` handler.

So in your case the code should be:

```tsx
useKeyboardHandler(
    {
      onMove: (event) => {
        'worklet'
        height.value = Math.max(event.height, 0)
      },
      onEnd: (event) => {
        'worklet'
        height.value = Math.max(event.height, 0)
      },
    },
    []
  )
```

Did I answer in the question?

**Comment by kimak** [comment]
Yes perfectly,  it's fixed now:
![Screenshot 2024-09-27 at 09 24 29](https://github.com/user-attachments/assets/8d6350ac-0e48-418f-ad4b-792ac0d91cb4)

thanks a lot for your works on this 🙇‍♂️

**Comment by kirillzyusko** [comment]
You are welcome @kimak 😊
