### ISSUE TITLE
Initial image jumping with expo-splashscreen when enabling navigationBarTranslucent (android)

### ISSUE THREAD

**Issue by LeunensMichiel** [kirillzyusko/react-native-keyboard-controller#615]
**Describe the bug**
I'm trying to make my app edge-to-edge compatible. However, when I try to make the navigation bar transparent, the logo jumps on initial app launch **(not when I hot-reload)**

You can see it here in action:

https://github.com/user-attachments/assets/7dbffa31-9c95-4aad-8f30-172c85f80f35

This is only when enabling `navigationBarTranslucent` on the `KeyboardProvider`. 

When I disable this, the jumping in the splashscreen goes away, but of course at the cost of my navbar not being transparent anymore.

However, I did notice that once the app is launched from a cold state, the jumping does not occur anymore when I hot reload (cmd + r) the app.

**Code snippet**

>  app.config (expo)

```js
        backgroundColor: "#044351",
	androidStatusBar: {
		translucent: true,
		barStyle: "light-content",
		backgroundColor: "#00000000"
	},
	androidNavigationBar: {
		backgroundColor: "#00000000"
	},
	splash: {
		image: "./assets/splash.png",
		resizeMode: "contain",
		backgroundColor: "#044351"
	},
	updates: {
		fallbackToCacheTimeout: 0
	},
	assetBundlePatterns: ["**/*"],
….
```

> app.shell.tsx

```tsx
<ReactQueryProvider>
	<PermissionsProvider>
		<SafeAreaProvider>
			<GestureHandlerRootView style={tw`flex-1`}>
				<KeyboardProvider
					navigationBarTranslucent
					statusBarTranslucent
				>
					<BottomSheetModalProvider>
						<App /> // I'm rendering an empty yellow screen in the example
						<Toast
						        config={customToasts}
							topOffset={20}
						/>
					</BottomSheetModalProvider>
				</KeyboardProvider>
			</GestureHandlerRootView>
		</SafeAreaProvider>
	</PermissionsProvider>
</ReactQueryProvider>
```

*System specs*
- MacOS Sonoma 14.7
- Device: Google Pixel 8 Simulator
- OS: Android 14
- RN version: 0.75.4
- RN architecture: old
- Library version: 1.14.0

**Comment by hirbod** [comment]
Thank me later

```js
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createRunOncePlugin, AndroidConfig, withStringsXml } = require('@expo/config-plugins')

// This plugin fixes the initial statusbar shifting when the android app is booting up.
const withAndroidSplashScreen = (expoConfig) =>
  withStringsXml(expoConfig, (modConfig) => {
    modConfig.modResults = AndroidConfig.Strings.setStringItem(
      [
        {
          _: 'true',
          $: {
            name: 'expo_splash_screen_status_bar_translucent',
            translatable: 'false',
          },
        },
      ],
      modConfig.modResults
    )
    return modConfig
  })

module.exports = createRunOncePlugin(withAndroidSplashScreen, 'android-splash', '1.0.0')
```

Make sure to use this config plugin if you're using Expo.

Config:

```json
    "androidNavigationBar": {
      "barStyle": "dark-content",
      "backgroundColor": "#00000000"
    },
    "androidStatusBar": {
      "barStyle": "dark-content",
      "backgroundColor": "#00000000",
      "translucent": true
    },
```

KeyboardProvider is using the same prop. Also set

```ts
  statusBarTranslucent: true,
  navigationBarColor: '#00000000',
```

in my StackNavigator (managed by react-native-screens).

**Comment by LeunensMichiel** [comment]
Hey, thanks for the suggestion!

Unfortunately this doesn't fix my splashscreen issue. (Although I've used the edge-to-edge problems inside of my app with configurations like yours).

**Comment by kirillzyusko** [comment]
> However, I did notice that once the app is launched from a cold state, the jumping does not occur anymore when I hot reload (cmd + r) the app.

I'm not sure I got this statement. Does jumping happens during development or on a release as well? Maybe you meant that jumping doesn't happen in ward state (i. e. when you hot reload the app)?

And may I ask you for a reproduction example? 👀 

Have you tried to use `react-native-bootsplash`? I remember this library stretches app to edge-to-edge by default so the issue may gone completely if you use other library for a bootsplash (though I understand that it requires a lot of effort to perform a migration). Or maybe you have any concerns for not using `react-native-bootsplash`?

**Comment by LeunensMichiel** [comment]
Hi!

Thanks for the answer. Unfortunately migrating to `react-native-bootsplash` isn't possible for now, but I think it would be nicer to get it running out of the box hehe.

https://github.com/LeunensMichiel/rn-kbc-bug/tree/main
I could reproduce it in a very minimal reproduction, hopefully that'll help you.

You can very clearly see it when delaying the splashscreen hiding with 
`ExpoSplashScreen.preventAutoHideAsync()`. You'll see a small "jump"

(not the most breaking bug of course haha). Could also be related to expo-splashscreen, but at this point I'm not so sure anymore. (Similar issue: https://github.com/expo/expo/issues/21036)

The jumping goes away if I either

- Remove `navigationBarTranslucent` prop or
- While app is loaded, reload the app (so when in a ward state)

**Comment by LeunensMichiel** [comment]
EDIT: Upon further testing I've noticed that if I remove the keyboard-controller dependency and explicitly set the navigation bar to transparent, the jumping also happens. So might be related to expo after all…

**Comment by zoontek** [comment]
@LeunensMichiel In order to prevent this / to migrate the ecosystem to edge-to-edge by default, we release [react-native-edge-to-edge](https://github.com/zoontek/react-native-edge-to-edge). For the moment, it has perfect compatibility with react-native-bootsplash. But I also teamed up with Expo, and [Expo 52 will finally fix splash screens issues](https://github.com/expo/expo/pull/23882) on Android.

**Comment by LeunensMichiel** [comment]
@zoontek sweet! I suppose a lot of stuff will change thanks to Android 15 (but in a good way). I suppose this can be closed for now as its still a bit too soon to fix this I suppose (as according to your links, this will be fixed upstream)

**Comment by kirillzyusko** [comment]
Cool! Thanks everyone for a contribution 💪 

I hope everything will be fixed in upstream and we will not see any annoying jumps anymore 🙈 

I'll close the issue, but if you get any new information and think that the problem should be re-opened - let me know and I'll re-open this issue.
