### ISSUE TITLE
[iOS] `OverKeyboardView` does not work when the keyboard is not active

### ISSUE THREAD

**Issue by thespacemanatee** [kirillzyusko/react-native-keyboard-controller#618]
**Describe the bug**

When I use this component, it works as expected on Android, but on iOS, the children of `OverKeyboardView` are invisible when the keyboard is not active. I know they are rendered because they show up in the element inspector and can be interacted with (buttons are still pressable).

I think this happens because `UIRemoteKeyboardWindow` is not available when the keyboard is not active, but I don't think it is expected for the contents to be invisible in such cases. If you look at Telegram, the popover can be opened whether or not the keyboard is active.

**Code snippet**

```tsx
<OverKeyboardView visible={popoverModalVisible}>
  <View
    className={cn('absolute inset-0', className)}
    accessibilityViewIsModal={popoverModalVisible}
    onAccessibilityEscape={onRequestClose}
    pointerEvents="box-none"
    style={style}>
    {popoverContent}
  </View>
</OverKeyboardView>
```

**Repo for reproducing**

Please let me know if you need a repro, but I believe it should be fairly easy to reproduce.

**To Reproduce**

I tried my best to run the example ios app but I'm getting this error:

<img width="972" alt="Screenshot 2024-10-08 at 12 07 57 AM" src="https://github.com/user-attachments/assets/b5ca23e4-2514-4749-bd10-1218f670c91a">

**Expected behavior**

When the keyboard is active, the children in `OverKeyboardView` should not be invisible.

**Screenshots**

### iOS

![simulator_screenshot_ABDF4AEB-BC2F-4088-AB87-DD494B823B18](https://github.com/user-attachments/assets/37b3f4b2-ed4d-47df-aa78-c69cfd06b21f)

### Android

![Screenshot_1728317773](https://github.com/user-attachments/assets/0c4d38c2-1481-439d-a255-d46a33e2a68b)

**Smartphone (please complete the following information):**

- Device: iPad mini
- OS: iOS 18.1
- RN version: 0.75.3
- RN architecture: Paper
- JS engine: Hermes
- Library version: 1.14.0

**Comment by kirillzyusko** [comment]
@thespacemanatee thank you for the issue!

Can you try to comment out a line in example/ios/Podfile with ccache_enabled, reinstall Pods and try again?

The thing is that in my example project everything works (i.e. view is shown even when the keyboard is not visible).
In case when the keyboard window is not available, then I am attaching a view to the last available window.

I am responding to you from a mobile device, so can't share any links, but if you can provide a reproduction example - it would help a lot.

In the example app I tested a scenario that you described and it was working well 🙈

**Comment by kirillzyusko** [comment]
I'm also using `@react-navigation/native-stack@6.11.0` and `react-native-screens@3.34.0` and just tested with native-stacks and it still works 🤷‍♂️ (the blue rectangle is in `OverKeyboardView`): https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/example/src/screens/Examples/OverKeyboardView/index.tsx

<img src="https://github.com/user-attachments/assets/e6025ca5-e18e-462c-b779-25b367b74c99" width="500">

<hr>

> I think this happens because UIRemoteKeyboardWindow is not available when the keyboard is not active, but I don't think it is expected for the contents to be invisible in such cases. 

I'm attaching to last window if keyboard window is not available: https://github.com/kirillzyusko/react-native-keyboard-controller/blob/bc8d3b7bbec9ff133dfa1e4a45c1924651ff93fd/ios/extensions/UIWindow.swift#L41

So yeah, really curious what is preventing this component from being working in your case 👀

**Comment by kirillzyusko** [comment]
Thank you for investigation @thespacemanatee ! Appreciate that!

Yeah, your code work well in example project - I left one comment what would be better to change, but overall I'm happy to have these changes 😊

**Comment by thespacemanatee** [comment]
@kirillzyusko I left a [comment](https://github.com/kirillzyusko/react-native-keyboard-controller/pull/621#discussion_r1792332882) here for posterity. I also wanted to add that it seems `OverKeyboardView` is inspired by [FullWindowOverlay](https://github.com/software-mansion/react-native-screens/blob/main/ios/RNSFullWindowOverlay.mm) from `react-native-screens` and I don't see the same conflicts with navigation and the overlay. I don't have the bandwidth to investigate further for now so I'm just noting this down for future work!

**Comment by kirillzyusko** [comment]
> I also wanted to add that it seems OverKeyboardView is inspired by [FullWindowOverlay](https://github.com/software-mansion/react-native-screens/blob/main/ios/RNSFullWindowOverlay.mm) from react-native-screens and I don't see the same conflicts with navigation and the overlay.

`FullWindowOverlay` was inspired by `Modal` implementation from `react-native` and I also used `Modal` implementation for a reference, so yeah, the implementation with `FullWindowOverlay` will be similar anyway 🙃
