### ISSUE TITLE
[Android] Modal overlay glitch when dismissing keyboard

### ISSUE THREAD

**Issue by shollington-rbi** [kirillzyusko/react-native-keyboard-controller#619]
<img align="right" src="https://github.com/user-attachments/assets/dc994c09-fd87-47ec-8e1c-eed956da2ad1" width="175" />Thank-you so much for creating this incredible library @kirillzyusko. It is by far the best React Native keyboard controller library and we're excited to swap out react-native-keyboard-aware-view.

We noticed an issue when attempting to integrate this into our app and was hoping you could help debug.

**Describe the bug**
The modal overlay no longer shades the full screen height when keyboard is dismissed at the same time as modal open.

**Code snippet**
You can reproduce with the repo's [example project](https://github.com/kirillzyusko/react-native-keyboard-controller/tree/main/example).

**To Reproduce**

1. Compile and run the example project with `yarn example android`.
2. Go to the `Modal` example.
3. Click "show modal" and observe that that overlay shades the *full* screen height.
4. Close modal and on the main screen, click the yellow keyboard input to make the keyboard shown.
5. With the keyboard still visible, click "show modal" again and observe the keyboard dismisses and the overlay no longer spans the full screen height.

**Expected behavior**
The modal overlay should shade the *full* height of the screen including the space that the keyboard used to occupy when it is dismissed.

**Screenshots**
See animated GIF to the right captured from Pixel 3a API 34 Emulator.

**Comment by kirillzyusko** [comment]
Thank you @shollington-rbi for the issue 🙌 

I'm aware about that, but haven't found a fix yet 😔 As a workaround you can use that code: https://github.com/kirillzyusko/react-native-keyboard-controller/issues/387#issuecomment-2002020998

And in a meantime I'll try to find a solution for that 👀

**Comment by kirillzyusko** [comment]
@shollington-rbi I published `1.14.1`! Feel free to try that 🙌

**Comment by shollington-rbi** [comment]
Works like a charm! Thank you so much!
