### ISSUE TITLE
useReanimatedKeyboardAnimation on Android always returns 0 for keyboard height after upgrade to React Native 0.74.6

### ISSUE THREAD

**Issue by a7mdkhaled** [kirillzyusko/react-native-keyboard-controller#628]
**Describe the bug**
Hello, After upgrading my React Native app to version 0.74.6, I encountered an issue on Android where `useReanimatedKeyboardAnimation` is not calculating the keyboard height correctly. The returned height is always 0.

Interestingly, when I use `useAnimatedKeyboard` from `react-native-reanimated`, it returns the correct keyboard height on Android.

**Code snippet**
```  
  // an example of what is happening using derived value and useAnimatedStyle

  import { useReanimatedKeyboardAnimation } from 'react-native-keyboard-controller';
  import { useAnimatedKeyboard } from 'react-native-reanimated';

  ... 

  const { height: KeyboardHeightFromReanimated } = useAnimatedKeyboard(); // react-native-reanimated

  const { height: KeyboardControllerHeight } = useReanimatedKeyboardAnimation(); // react-native-keyboard-controller
 

  const handleHeightChange = (KeyboardHeightFromReanimated: number, KeyboardControllerHeight: number ) => {
  console.log({KeyboardHeightFromReanimated}) // This one is returning the correct height
  console.log({KeyboardControllerHeight}) // logs 0
  };

  useDerivedValue(() => {
    runOnJS(handleHeightChange)(KeyboardHeightFromReanimated.value,  KeyboardControllerHeight.value );
  });

  const styles = useAnimatedStyle(() => {
    console.log({ReactNativeControllerHeight: KeyboardControllerHeight.value}); // logs 0
    console.log({ReanimatedHeight: KeyboardHeightFromReanimated.value}); // This one is returning the correct height
    
    return {
      height: KeyboardHeightFromReanimated.value, // working
    };

  // return {
  //   height:KeyboardControllerHeight.value, // not working
  // };
  }, []);
  
  return <Reanimated.View style={styles} />;
```

**To Reproduce**
- Upgrade React Native to 0.74.6.
- Use useReanimatedKeyboardAnimation in a component to track the keyboard height.
- Run the app on an Android device or emulator.
- Trigger the keyboard (e.g., focus on a TextInput).
- Observe that the keyboard height returned by useReanimatedKeyboardAnimation is always 0.

**Expected behavior**
- The keyboard height should be correctly calculated on Android when using useReanimatedKeyboardAnimation.

**Smartphone (please complete the following information):**

- Device: Android (Emulator and Physical Devices)
- RN version: 0.74.6
- RN architecture: old
- JS engine: Hermes
- Library version: 1.14.0
- react-native-reanimated: 3.15.4
- react-native: 0.74.6

**Additional context**
- This issue started after upgrading to React Native 0.74.6.
- I have upgraded react-native-keyboard-controller to the latest version (1.14.0), but the issue is still happening.
- The issue only occurs on Android, while on iOS, the height is calculated correctly.

**Comment by kirillzyusko** [comment]
@a7mdkhaled ah, very interesting! Can you create a minimal reproduction example? In this case I can quickly investigate the problem 👀 

Maybe you also updated `react-native-screens` and using `navigationBar*` props from `react-native-screens` by any chance?

**Comment by a7mdkhaled** [comment]
Hey @kirillzyusko, Yup, it doesn't work if I have status bar styles set in the screen options of react-navigation::

```
navigationBarColor: 'red',
statusBarTranslucent: true,
statusBarStyle: 'dark',
statusBarColor: 'transparent',
```
It works if I remove `statusBarTranslucent`, but then the status bar won't be transparent, is this a known issue? can I workaround it? It used to work before upgrading tho.

Here is a repro if you still need it:

https://github.com/a7mdkhaled/KeyboardIssueRepro

**Comment by kirillzyusko** [comment]
@a7mdkhaled I'll have a look on it, but may I ask you to follow this conversation https://github.com/software-mansion/react-native-screens/pull/2301 and apply a patch in your project locally?

These options I test in my example project: https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/example/src/navigation/NestedStack/index.tsx#L17-L19 and they work (it's even covered with e2e tests 💪)

But it's worth to note that I'm using a patched version of `react-native-screens` https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/example/patches/react-native-screens%2B3.34.0.patch

**Comment by a7mdkhaled** [comment]
Hey @kirillzyusko!

I applied a patch with the change from https://github.com/software-mansion/react-native-screens/pull/2301, and it fixed the issue! Thank you!

**Comment by kirillzyusko** [comment]
Nice @a7mdkhaled 

I think you need to keep it for some time (the fix was merged in upstream, you just need to wait for a new release) and when 3.35 will be released you can remove the patch and update the library version in `package.json`

I'll close the issue, but if you found a new problems - feel free to open new issue 🙌
