### ISSUE TITLE
OverKeyboardView freezes when (Native) Stack Navigator child Screens changes

### ISSUE THREAD

**Issue by thespacemanatee** [kirillzyusko/react-native-keyboard-controller#632]
**Describe the bug**

Say I have a simple Home screen guarded by an Auth screen using conditional rendering, if the `OverKeyboardView` is visible and the navigator conditionals change resulting in the Screens changing, the `OverKeyboardView` will be stuck on the screen.

However, if the keyboard is present when the conditionals change, the `OverKeyboardView` does not get stuck.

**Code snippet**

```ts
<Stack.Navigator>
  {isLoggedIn ? (
    <Stack.Screen name="Home" component={HomeScreen} />
  ) : (
    <Stack.Screen name="Login" component={LoginScreen} />
  )}
</Stack.Navigator>
```

with this [example](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/example/src/screens/Examples/OverKeyboardView/index.tsx).

**Repo for reproducing**

https://github.com/thespacemanatee/rnkc-repro

**To Reproduce**

1. Click on 'Login'
2. Click on 'Show' (Do not present the keyboard first, the bug will not occur if the keyboard is present)
3. Click on 'Logout'
4. The `OverKeyboardView` is stuck

**Expected behavior**

The `OverKeyboardView` is not stuck

**Screenshots**

### Keyboard Inactive (Unexpected)

https://github.com/user-attachments/assets/0ef323bf-c23e-438d-9536-c003d782b6fe

### Keyboard Active (Expected)

https://github.com/user-attachments/assets/06d536f1-6a6e-4e5e-a6bb-c45349a18e72

**Smartphone (please complete the following information):**

- Desktop OS: MacOS 15.1 beta
- Device: iPhone 16
- OS: iOS 18.1
- RN version: 0.75.3
- RN architecture: Paper
- JS engine: Hermes
- Library version: 1.14.1

**Additional context**
Related to https://github.com/kirillzyusko/react-native-keyboard-controller/pull/621#discussion_r1792332882

**Comment by kirillzyusko** [comment]
Thanks @thespacemanatee for a detailed reproduction example and all the info in the issue! I appreciate it!

Would you mind to test if https://github.com/kirillzyusko/react-native-keyboard-controller/pull/633 fixes the problem? I tested in your example and it works as expected, I believe 🙃

**Comment by thespacemanatee** [comment]
@kirillzyusko that's fantastic, I can confirm it works on my setup and it no longer freezes in this way. It still doesn't resolve the issue in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/621#discussion_r1792332882 but I think this brings us closer to fixing that as well!
