### ISSUE TITLE
OverKeyboardView conflicts with Expo Web Browser and potentially other native View Controllers

### ISSUE THREAD

**Issue by thespacemanatee** [kirillzyusko/react-native-keyboard-controller#635]
**Describe the bug**
Related to https://github.com/kirillzyusko/react-native-keyboard-controller/pull/621#discussion_r1792332882

I have finally found a way to reproduce this issue with the example code and some minor modifications to the previous repro in #632.

The problem is when we show the in-app browser with Expo Web Browser and dismiss it, the `UIRemoteKeyboardWindow` somehow returns non-nil, even though the keyboard has never been shown before. Presenting the keyboard "unstucks" this and `UIRemoteKeyboardWindow` becomes correctly nil again after the keyboard is dismissed. I have added some logging in the patch file to help you in debugging this issue.

I think this approach might also affect usage with other types of native views that I am unaware of. Expo Web Browser uses `SFSafariViewController` internally.

**Code snippet**
```tsx
<Button
  title="Show web browser"
  onPress={() =>
    WebBrowser.openBrowserAsync(
      "https://kirillzyusko.github.io/react-native-keyboard-controller/docs/installation#troubleshooting"
    )
  }
/>
```

**Repo for reproducing**
https://github.com/thespacemanatee/rnkc-repro/commit/01aa72dec3bda2e154c7b082bc9f65e050e87fef

**To Reproduce**

1. Click on "Login"
2. Click on "Show web browser"
3. Click on "Done" on the top left corner
4. Click on "Show"
5. `OverKeyboardView` is rendered with invisible child. Click once to dismiss.

**Continuation**

6. Click on the (yellow) text input field
7. Click on "Show" again
8. `OverKeyboardView` is rendered with visible child.

**Expected behavior**
After dismissing the in-app browser, clicking on "Show" should render `OverKeyboardView` with visible children. `UIRemoteKeyboardWindow` should be nil at this time.

**Screenshots**

https://github.com/user-attachments/assets/a78baaa4-e1bd-43d4-ad76-853193461b76

**Smartphone (please complete the following information):**

- Desktop OS: MacOS 15.1
- Device: iPhone 16.1
- OS: iOS 18.1
- RN version: 0.75.3
- RN architecture: Paper
- JS engine: Hermes
- Library version: 1.14.1

**Comment by thespacemanatee** [comment]
@kirillzyusko This [thread](https://forums.developer.apple.com/forums/thread/707262) seems relevant. Apparently what we are doing here is "hacky" and Apple isn't so happy about it. According to this [comment](https://forums.developer.apple.com/forums/thread/707262?answerId=715613022#715613022), `SFSafariViewController` is run out of the app process(?)

**Comment by kirillzyusko** [comment]
Thanks @thespacemanatee for a decent reproduction example! I'll try to run it today and see what's going wrong!

**Comment by kirillzyusko** [comment]
@thespacemanatee would you mind checking if https://github.com/kirillzyusko/react-native-keyboard-controller/pull/636 fixes the problem? Example app works good 🙃

**Comment by thespacemanatee** [comment]
@kirillzyusko nice one man, works in my company project as well. No more bugs for me to report for now, thank you so much sir 😄

**Comment by kirillzyusko** [comment]
@thespacemanatee woohoo 🎉 Glad to hear that! 3 fixes in row and component finally works (the funny thing is that it was only iOS issues) 😂 

But anyway, I'm glad that it works 😊 I'll merge this PR today/tomorrow and most likely new release will be published closer to Friday 🙃  In a meantime you can `patch-package` the library and apply all necessary changes locally 🚀

**Comment by thespacemanatee** [comment]
@kirillzyusko another small issue that you can consider looking into: reloading the app while `OverKeyboardView` is visible will cause to stay stuck on the screen. Perhaps the fix will be similar to the lifecycle solution in the recent PR 😄

**Comment by kirillzyusko** [comment]
> another small issue that you can consider looking into: reloading the app while OverKeyboardView is visible will cause to stay stuck on the screen. Perhaps the fix will be similar to the lifecycle solution in the recent PR 😄

@thespacemanatee Created an issue to track a progress https://github.com/kirillzyusko/react-native-keyboard-controller/issues/637 👀
