### ISSUE TITLE
`OverKeyboardView` stays on screen even after js-reload

### ISSUE THREAD

**Issue by kirillzyusko** [kirillzyusko/react-native-keyboard-controller#637]
**Describe the bug**

**Code snippet**

Reproducible in `OverKeyboardView` example.

**Repo for reproducing**

you can use example app.

**To Reproduce**

1. Go to `OverKeybaordView` example
2. Click on 'Show'
3. Press `cmd`+`ctrl`+`z` and select Reload.
4. See the view present on the screen.

**Expected behavior**

View should be unmounted, because we reload entire app.

**Screenshots**

https://github.com/user-attachments/assets/8e3ae0ba-aab5-498b-adbd-d0a5d154ef1c

**Smartphone (please complete the following information):**

- Desktop OS: MacOS 14.6.1
- Device: iPhone 15 Pro
- OS: iOS 17.5
- RN version: 0.74.3
- RN architecture: old (haven't tested new)
- JS engine: Hermes
- Library version: 1.14.1

**Additional context**

Most likely an important lifecycle method with corresponding cleanup is not implemented.

**Comment by kirillzyusko** [comment]
@thespacemanatee  would you mind to test https://github.com/kirillzyusko/react-native-keyboard-controller/pull/638 ? 😅

**Comment by thespacemanatee** [comment]
@kirillzyusko it works, nice one!
