### ISSUE TITLE
Reanimated warning regarding `value` render during component render.

### ISSUE THREAD

**Issue by akuul** [kirillzyusko/react-native-keyboard-controller#649]
**Describe the bug**
Since `React Native Reanimated v3.16.0` changed it's logger, I'm getting 
```bash
[Reanimated] Reading from `value` during component render. Please ensure that you do not access the value` property or use `get` method of a shared value while React is rendering a component.
```
when using `KeyboardAwareView` component. Currently there are few packages having this problem with open issues like `@gorhom/react-native-bottom-sheet` or `react-native-pager-view`.

This seems to be related to `KeyboardAvoidingView/hooks.ts` where it uses context to get `reanimated` value from `useKeyboardContext()` hook. 

Very quick playaround with the snippet below fixes the warning, but this doesn't look like ideal solution.

```typescript
  const heightWhenOpened = useSharedValue(0);
  const height = useSharedValue(0);
  const progress = useSharedValue(0);
  const isClosed = useSharedValue(true);

  useEffect(() => {
    heightWhenOpened.value = -reanimated.height.value;
    height.value = -reanimated.height.value;
    progress.value = reanimated.progress.value;
    isClosed.value = reanimated.progress.value === 0;
  }, []);
  ```

**Code snippet**
```typescript
function App() {
  return (
    <KeyboardProvider>
      <KeyboardAvoidingView></KeyboardAvoidingView>
    </KeyboardProvider>
  );
}

export default App;

```
**Expected behavior**
React Native Reanimated should not throw an error

**Screenshots**
![image](https://github.com/user-attachments/assets/36bc9061-0f52-4b52-b664-c956993eda58)

**Smartphone (please complete the following information):**

- RN version: 0.75.4
- RN architecture: Old
- JS engine: Hermes
- Library version: 1.14.2

**Additional context**
This issue does not appear with `KeyboardAwareScrollView`.

**Comment by kirillzyusko** [comment]
Okay, interesting, thank you @akuul 🙌 

I'll have a look on that 👀 

> This seems to be related to KeyboardAvoidingView/hooks.ts where it uses context to get reanimated value from useKeyboardContext() hook.

You are right, this code triggers that. But I do not understand this restriction, because I know that only for `ref` variables it's not recommended to read/mutate `.current` value. Regarding `useSharedValue` - it's based on `useState`, so I don't understand yet why it's forbidden to read `.value` yet.

But thank you for opening the issue ❤️ I'll figure out how to re-work the code to fix it!

**Comment by antFrancon** [comment]
Hi,
If you need to access a shared value inside React lifecycle methods only for initializing other shared values, I think this workaround may fit better than a `useEffect`:"
```ts
  const [initialHeight] = useState(() => reanimated.height.value);
  const [initialProgress] = useState(() => reanimated.progress.value);

  const heightWhenOpened = useSharedValue(-initialHeight);
  const height = useSharedValue(-initialHeight);
  const progress = useSharedValue(initialProgress);
  const isClosed = useSharedValue(initialProgress === 0);
```

**Comment by kirillzyusko** [comment]
Hi @antFrancon 

Thank you for idea! I had several ideas:
- to add those values (initialHeight + initialProgress) into `useMemo`;
- to create custom `useLazySharedValue` hook with syntax as `useLazySharedValue(() => reanimated.height.value)` (and it would execute this callback only once, this callback would be simply called in `useState` hook).

But your idea also sounds fresh! Will keep it mind!
