### ISSUE TITLE
KeyboardAvoidingView doesn't work on Android

### ISSUE THREAD

**Issue by gkassym** [kirillzyusko/react-native-keyboard-controller#650]
**KeyboardAvoidingView doesn't work on Android**

I installed the react-native-keyboard-controller library and ran pod install. I wrapped the root component with KeyboardProvider, and everything works as expected on iOS. However, on Android, it doesn't work at all. I also tried using KeyboardAwareScrollView, but encountered the same issue—it doesn't work. Then, I attempted to use KeyboardEvents, but the listener callback doesn't trigger when the keyboard opens or closes. As mentioned, iOS works perfectly. I performed a clean build, cleared the Android/app build, cleaned the Gradle files, and removed node_modules, but none of these steps resolved the problem.

I believe the native code wasn't installed correctly. Any ideas?

**Code snippet**
```tsx
export function MessagingScreen(): JSX.Element {
  useEffect(() => {
    const show = KeyboardEvents.addListener('keyboardWillShow', (e) => {
      console.log('keyboardWillShow---------------', e); // <- doesn't trigger
    });

    return () => {
      show.remove();
    };
  }, []);

  return (
    <KeyboardAvoidingView
      contentContainerStyle={styles.container}
      style={styles.content}
      behavior="padding"
      keyboardVerticalOffset={400}>
      <View style={styles.inner}>
        <Text style={styles.heading}>Header</Text>
        <View>
          <TextInput placeholder="Username" style={styles.textInput} />
          <TextInput placeholder="Password" style={styles.textInput} />
        </View>
        <TouchableOpacity style={styles.button}>
          <Text style={styles.text}>Submit</Text>
        </TouchableOpacity>
      </View>
    </KeyboardAvoidingView>
  );
}
```
**Screenshots**

https://github.com/user-attachments/assets/d8ccb0eb-712c-4400-8367-28338b800189

**Smartphone (please complete the following information):**

RN version: 0.75.3
RN architecture: Old
JS engine: Hermes
Library version: 1.14.2
React-native-reanimated: 3.16.1

**Additional context**

**Comment by kirillzyusko** [comment]
@gkassym do you use `react-native-screens`/`native-stack` by any chance? If yes, then which version of `react-native-screens` are you using (which version is specified in `.lock` file)? Do you use `navigationBar*` properties from `native-stack` by any chance?

**Comment by gkassym** [comment]
Yes, i use:
- react-native-screens: "^3.34.0"
- @react-navigation/native: "^6.1.4"
- @react-navigation/native-stack: "^6.9.10"
- @react-navigation/stack: "^6.3.16"
- pnpm: "9.10.0"
- node: "v18.20.2"

Also i noticed this warning: 
`Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.`
Could this have any impact?

**Comment by kirillzyusko** [comment]
> Also i noticed this warning:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
Could this have any impact?

I don't think so 🙂 

Can you try to apply a patch from https://github.com/software-mansion/react-native-screens/pull/2301 and re-build the project? It may solve the problem 🙂

**Comment by gkassym** [comment]
I applied the patch you recommended. It works. 👍

**Comment by gkassym** [comment]
But in the Android app there is a weird line at the top. If I do `KeyboardProvider enabled={false}` it disappears. What is it?
<img width="311" alt="Screenshot 2024-10-23 at 15 32 12" src="https://github.com/user-attachments/assets/7ecc104f-4d7c-4e60-9681-f4154118efd4">

**Comment by kirillzyusko** [comment]
> But in the Android app there is a weird line at the top. If I do KeyboardProvider enabled={false} it disappears. What is it?

@gkassym did you try to add `statusBarTranslucent` property to `KeyboardProvider`? Does it solve the problem?

**Comment by gkassym** [comment]
Nice 🔥 statusBarTranslucent works.

Another thing I noticed is that the keyboard opens first and then it moves the text input. Have you seen anything like this?

https://github.com/user-attachments/assets/8ff27e59-08c4-43a6-a88f-dc67cee79470

**Comment by kirillzyusko** [comment]
Yes @gkassym 

It happens if you animate `height`/`padding` or any other non-UI props on Android. If you want to have a perfect animation synchronization then you can use https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/example/src/screens/Examples/ReanimatedChat/index.tsx as a reference - in this example I'm animating `translateY` and it works frame-in-frame 👀 

I believe I answered on your questions and the conversation goes into a different direction - can I close this issue?
If you encounter any other problem don't hesitate to open a new issue - I will be happy to help and guide you 😊

**Comment by gkassym** [comment]
Hi @kirillzyusko, wow, nice. I will check. Thanks 🔥
