### ISSUE TITLE
Use blur() in useKeyboardHandler to unfocus; report errors

### ISSUE THREAD

**Issue by TallNutAlt** [kirillzyusko/react-native-keyboard-controller#671]
`  useKeyboardHandler(
    {
      onEnd: e => {
        'worklet';
        if (e.height === 0) {
          inputRef.current?.blur();
        }
      },
    },
    [],
  );`
  
  
  ReanimatedError: [Reanimated] Trying to access property `blur` of an object which cannot be sent to the UI runtime., js engine: reanimated
  
"react-native": "0.72.4",
"react-native-keyboard-controller": "^1.14.3",
  
  When a Textinput is focused and the height in useKeyboardHandler is 0, it will cancel the focus error

**Comment by TallNutAlt** [comment]
Wrapped by KeyboardAvoidangView

**Comment by TallNutAlt** [comment]
https://github.com/user-attachments/assets/4f02926e-2da7-49f1-93a1-abc01881e34f

**Comment by TallNutAlt** [comment]
To address this issue This issue might be related to facebook/react-native#19366.

**Comment by kirillzyusko** [comment]
Hi @TallNutAlt 

You can not use react refs directly in worklets. So basically you have two choices:

### 1️⃣ Declare JS function and call it via `runOnJS`

```tsx
const blurInput = () => {  inputRef.current?.blur(); }

useKeyboardHandler( { onEnd: e => { 'worklet'; if (e.height === 0) { runOnJS(blurInput)() } }, }, [], );
```

### 2️⃣ use `useAniamtedRef` + `dispatchCommand`

```tsx
const animatedRef = useAnimatedRef();

useKeyboardHandler( { onEnd: e => { 'worklet'; if (e.height === 0) { dispatchCommand(animatedRef, 'blur'); } }, }, [], );

<AnimatedTextInput ref={animatedRef}
```

Docs for a reference: https://docs.swmansion.com/react-native-reanimated/docs/advanced/dispatchCommand
