### ISSUE TITLE
During back navigation in Stack Navigator, KeyboardToolba from the parent screen is also animating 

### ISSUE THREAD

**Issue by RobertPetricevic** [kirillzyusko/react-native-keyboard-controller#716]
**Describe the bug**

If both screens in the stack navigator include the KeyboardToolbar, navigating back causes the toolbar from the previous screen to appear and dismiss in the background.

https://github.com/user-attachments/assets/73efbff8-a260-4885-8292-e3c603cce1ca

**Comment by kirillzyusko** [comment]
@RobertPetricevic can you check if using changes from https://github.com/kirillzyusko/react-native-keyboard-controller/pull/717 fixes the problem?

You'd need to use `enabled` property as:

```tsx
const isFocused = useIsFocused();

return <KeyboardStickyView enabled={isFocused} />
```

**Comment by RobertPetricevic** [comment]
@kirillzyusko After applying changes I got this:


https://github.com/user-attachments/assets/d0402ea2-d11d-4158-b05e-0ebb2f9bed30

I changed this code inside KeyboardStickyView:

`const stickyViewStyle = useAnimatedStyle(() => {
      const offset = interpolate(progress.value, [0, 1], [closed, opened]);

      return {
        transform: [{ translateY:isFocused ? (height.value + offset) : offset }],
      };
    }, [closed, opened, isFocused]);`
    

https://github.com/user-attachments/assets/01f80257-e56c-4779-ac85-e308cb6b7235

**Comment by kirillzyusko** [comment]
@RobertPetricevic smart! Indeed, we need to take an offset into consideration. But I think the code should be like this:

```tsx
transform: [{ translateY: enabled ? height.value + offset : closed }],
```

I. e. when `enabled={false}` then we need to apply `closed` offset (not entire `offset` as entire `offset` still computed by `progress.value` which is changing when you move the screen via gesture).

Can you confirm that such fix works as expected (with `closed` instead of `0`)?

**Comment by RobertPetricevic** [comment]
@kirillzyusko  aah yeas, make sense

yes, it working as expected :)
