### ISSUE TITLE
Disable debug infos (keyboardDidHide with no listeners registered etc)

### ISSUE THREAD

**Issue by hirbod** [kirillzyusko/react-native-keyboard-controller#8]
The current alpha does spam a lot with debug infos (like ::keyboardDidHide with no listeners registered)
I don't need those listeners, the warnings are annoying a bit. I had to disable them via yellow box

**Comment by kirillzyusko** [comment]
Hi @hirbod 

Thank you for the issue! I think I had the same problem and simply ignored it via `LogBox` (I know it's not perfect solution) 🙈

Seems like I fixed a problem in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/9 Could you give a try and confirm, that it actually fixes the issue? In my example app it works good and I don't see annoying warnings anymore 😊

**Comment by hirbod** [comment]
Looks like it is working :). I finally migrated to your library and tossed react-native-ui-lib in the trash :D

**Comment by kirillzyusko** [comment]
@hirbod nice, glad it fixes the problem 😊 I will shortly publish new version `alpha.1` which will include this fix - want to have small iterations for `alpha` releases :)
