### ISSUE TITLE
Crashes on iOS 15

### ISSUE THREAD

**Issue by OmgDef** [kirillzyusko/react-native-keyboard-controller#93]
The app crashes right before keyboard is shown on iOS 15. On iOS 16 it works just fine.
Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value

**Smartphone (please complete the following information):**
 - Desktop OS: MacOS 12.6.1
 - Device: iOS Simulator 
 - OS: iOS 15.0
 - RN version: 0.70.4
 - RN architecture: old
 - JS engine: Hermes
 - Library version: 1.4.0
<img width="916" alt="Снимок экрана 2022-10-28 в 17 40 57" src="https://user-images.githubusercontent.com/6762337/198558306-5585e9f7-1455-4383-a6f8-d0584363885a.png">

**Comment by kirillzyusko** [comment]
@OmgDef it happens exactly on iOS 15.0? Nor 15.6 - exactly 15.0?

I'm asking because i've tested app on iOS 15.6 and everything worked correctly 🤷‍♂️

**Comment by OmgDef** [comment]
@kirillzyusko I could not repeat the issue on a fresh project. It seems there is a conflict with one of my dependencies.

**Comment by kirillzyusko** [comment]
@OmgDef okay, let me know if you find a conflict and don't hesitate to re-open this issue or create a new one 🙂

**Comment by bcgilliom** [comment]
We had one user hit this on an iphone 15 Max, iOS 17.2.1. We are using version `1.10.3` of RNKC:

```
Thread 0 - (TH_STATE_WAITING)
0  Trusted +0x5746c0        Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value (KeyboardMovementObserver.swift:109:65)
1  Trusted +0x5705cc        KeyboardMovementObserver.observeValue(forKeyPath:of:change:context:) (<compiler-generated>)
2  Foundation +0x99e54      _NSKeyValueNotifyObserver
3  Foundation +0x99cf0      _NSKeyValueDidChange
4  Foundation +0x99b20      -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:]
5  Foundation +0x99850      -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:]
6  Foundation +0x12cb94     __NSSetPointValueAndNotify
7  UIKitCore +0x615f4       -[UIView(Geometry) _applyISEngineLayoutValuesToBoundsOnly:]
8  UIKitCore +0x60e44       -[UIView(Geometry) _resizeWithOldSuperviewSize:]
9  CoreFoundation +0x353f0  ___NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__
```

**Comment by kirillzyusko** [comment]
@bcgilliom can you check if https://github.com/kirillzyusko/react-native-keyboard-controller/pull/359 fixes the problem?
