### ISSUE TITLE
in example AwareScrollView example 84 when we click on text input like 7 or above the screen is not scrolling... any suggestion how can I achieve that

### ISSUE THREAD

**Issue by thtRajasthaniGuy** [kirillzyusko/react-native-keyboard-controller#99]
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/33393692/202435278-da92e0a4-ceec-40f8-be8e-55c5d3070e73.gif)

Thanks for the amazing library.

**Comment by kirillzyusko** [comment]
Hi @partTimeCoder96 
A quick question - what device are you using? Is it Samsung?

**Comment by partTimeCoder96** [comment]
no its realme x7 pro.

**Comment by kirillzyusko** [comment]
@partTimeCoder96 okay, got it. Would you mind to tell me whether other examples are working?
For example what happens if you open "Keyboard animation ⌨️"?

I have an assumption, that `useKeyboardAnimation` hook may return animated values that are not updating its values when keyboard is shown.

**Comment by partTimeCoder96** [comment]
no, it's not working.
one thing more I want to use AwareScroll View as a reusable component. how can I achieve that can you please give some example?

**Comment by IvanIhnatsiuk** [comment]
@partTimeCoder96 Do you use `GestureHandlerRootView` component? If yes, then I found a solution for me I just placed `KeyboardControllerProvider` under the `GestureHandlerRootView`. So your code should look like this:

```tsx
    <GHRootView>
      <KeyboardProvider>
        ...    
      </KeyboardProvider>
    </GHRootView>
```

**Comment by kirillzyusko** [comment]
@thtRajasthaniGuy seems like you were not running an example app. In `1.4.3` I fixed an issue, when you install a dependency into bare project and hook is not responding to keyboard size changes. You can try to use latest `1.4.3` version and see if it fixes your issue or not.

Regarding AwareScrollView as a reusable component - I will update example app and extract it to reusable component!
